// Copyright © 2022 Cerence Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the “Software”),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

syntax = "proto3";

package cerence.cloudservices.domain.common.content.media.v1;

import "google/api/field_behavior.proto";
import "cerence/cloudservices/domain/common/content/media/v1/visual_content.proto";

option go_package = "cerence/cloudservices/domain/common/content/media/v1";
option java_multiple_files = true;
option java_outer_classname = "GenresProto";
option java_package = "com.cerence.cloudservices.domain.common.content.media.v1";

message Genre{
  GenreEnum genre=1;

  string genre_name=2;

  repeated VisualContent media=3;
}

enum GenreEnum{
  GENRE_ENUM_UNSPECIFIED = 0;
  GENRE_ENUM_A_CAPPELLA = 1;
  GENRE_ENUM_ACID_HOUSE = 2;
  GENRE_ENUM_ACID_JAZZ = 3;
  GENRE_ENUM_ACOUSTIC = 4;
  GENRE_ENUM_ACOUSTIC_BLUES = 5;
  GENRE_ENUM_ADULT_CONTEMPORARY = 6;
  GENRE_ENUM_AFRICAN = 7;
  GENRE_ENUM_AFROBEAT = 8;
  GENRE_ENUM_ALBUM_ROCK = 9;
  GENRE_ENUM_ALTERNATIVE = 10;
  GENRE_ENUM_ALTERNATIVE_COUNTRY = 11;
  GENRE_ENUM_ALTERNATIVE_DANCE = 12;
  GENRE_ENUM_ALTERNATIVE_HIP_HOP = 13;
  GENRE_ENUM_ALTERNATIVE_METAL = 14;
  GENRE_ENUM_ALTERNATIVE_ROCK = 15;
  GENRE_ENUM_AMBIENT = 16;
  GENRE_ENUM_ANIME_MUSIC = 17;
  GENRE_ENUM_ANTI_FOLK = 18;
  GENRE_ENUM_ARAB_POP = 19  [deprecated = true];
  GENRE_ENUM_ART_ROCK = 20;
  GENRE_ENUM_ATMOSPHERIC_BLACK_METAL = 21;
  GENRE_ENUM_AUDIO_BOOK = 22;
  GENRE_ENUM_AUSTRALIAN_ALTERNATIVE_ROCK = 23  [deprecated = true];
  GENRE_ENUM_AUSTRALIAN_HIP_HOP = 24  [deprecated = true];
  GENRE_ENUM_AVANT_GARDE = 25;
  GENRE_ENUM_AVANT_GARDE_JAZZ = 26;
  GENRE_ENUM_AVANTGARDE_METAL = 27;
  GENRE_ENUM_AXE = 28;
  GENRE_ENUM_AZONTO = 29;
  GENRE_ENUM_BACHATA = 30;
  GENRE_ENUM_BACKGROUND = 31;
  GENRE_ENUM_BAILE_FUNK = 32;
  GENRE_ENUM_BALKAN_BRASS = 33;
  GENRE_ENUM_BALLET = 34;
  GENRE_ENUM_BANDA = 35;
  GENRE_ENUM_BAROQUE = 36;
  GENRE_ENUM_BASS_MUSIC = 37;
  GENRE_ENUM_BEBOP = 38;
  GENRE_ENUM_BHANGRA = 39;
  GENRE_ENUM_BIG_BAND = 40;
  GENRE_ENUM_BIG_BEAT = 41;
  GENRE_ENUM_BLACK_METAL = 42;
  GENRE_ENUM_BLUEGRASS = 43;
  GENRE_ENUM_BLUES = 44;
  GENRE_ENUM_BLUES_ROCK = 45;
  GENRE_ENUM_BOLERO = 46;
  GENRE_ENUM_BOOGALOO = 47;
  GENRE_ENUM_BOOGIE_WOOGIE = 48;
  GENRE_ENUM_BOSSA_NOVA = 49;
  GENRE_ENUM_BOUNCE = 50;
  GENRE_ENUM_BRASS_BAND = 51;
  GENRE_ENUM_BRAZILIAN_POP_MUSIC = 52  [deprecated = true];
  GENRE_ENUM_BREAKBEAT = 53;
  GENRE_ENUM_BREAKCORE = 54;
  GENRE_ENUM_BRILL_BUILDING_POP = 55;
  GENRE_ENUM_BRITISH_BLUES = 56  [deprecated = true];
  GENRE_ENUM_BRITISH_FOLK = 57  [deprecated = true];
  GENRE_ENUM_BRITISH_INVASION = 58;
  GENRE_ENUM_BRITISH_POP = 59  [deprecated = true];
  GENRE_ENUM_BROKEN_BEAT = 60;
  GENRE_ENUM_BRUTAL_DEATH_METAL = 61;
  GENRE_ENUM_BUBBLEGUM_DANCE = 62;
  GENRE_ENUM_BUBBLEGUM_POP = 63;
  GENRE_ENUM_C_POP = 64;
  GENRE_ENUM_CABARET = 65;
  GENRE_ENUM_CALYPSO = 66;
  GENRE_ENUM_CAMPUS = 67;
  GENRE_ENUM_CANTERBURY_SCENE = 68;
  GENRE_ENUM_CANTONESE_LANGUAGE = 69  [deprecated = true];
  GENRE_ENUM_CCM = 70;
  GENRE_ENUM_CELTIC = 71;
  GENRE_ENUM_CELTIC_ROCK = 72;
  GENRE_ENUM_CHAMBER_POP = 73;
  GENRE_ENUM_CHANSON = 74;
  GENRE_ENUM_CHICAGO_BLUES = 75;
  GENRE_ENUM_CHICAGO_HOUSE = 76;
  GENRE_ENUM_CHICAGO_SOUL = 77;
  GENRE_ENUM_CHICANO_RAP = 78;
  GENRE_ENUM_CHILDREN = 79;
  GENRE_ENUM_CHILL_OUT = 80;
  GENRE_ENUM_CHILLWAVE = 81;
  GENRE_ENUM_CHINESE_INDIE_ROCK = 82  [deprecated = true];
  GENRE_ENUM_CHINESE_STYLE = 83  [deprecated = true];
  GENRE_ENUM_CHINESE_TRADITIONAL = 84  [deprecated = true];
  GENRE_ENUM_CHIPTUNE = 85;
  GENRE_ENUM_CHORAL = 86;
  GENRE_ENUM_CHORO = 87;
  GENRE_ENUM_CHRISTIAN_ALTERNATIVE_ROCK = 88;
  GENRE_ENUM_CHRISTIAN_HARDCORE = 89;
  GENRE_ENUM_CHRISTIAN_HIP_HOP = 90;
  GENRE_ENUM_CHRISTIAN_METAL = 91;
  GENRE_ENUM_CHRISTIAN_MUSIC = 92;
  GENRE_ENUM_CHRISTIAN_PUNK = 93;
  GENRE_ENUM_CHRISTIAN_ROCK = 94;
  GENRE_ENUM_CHRISTMAS = 95;
  GENRE_ENUM_CLASSIC = 96;
  GENRE_ENUM_CLASSIC_FUNK_ROCK = 97;
  GENRE_ENUM_CLASSIC_GARAGE_ROCK = 98;
  GENRE_ENUM_CLASSIC_HITS = 99;
  GENRE_ENUM_CLASSIC_ROCK = 100;
  GENRE_ENUM_CLASSIC_RUSSIAN_ROCK = 101  [deprecated = true];
  GENRE_ENUM_CLASSICAL = 102;
  GENRE_ENUM_CLASSICAL_PERIOD = 103;
  GENRE_ENUM_COMEDY = 104;
  GENRE_ENUM_CONCERT = 105;
  GENRE_ENUM_CONTEMPORARY_COUNTRY = 106;
  GENRE_ENUM_COOL_JAZZ = 107;
  GENRE_ENUM_COUNTRY = 108;
  GENRE_ENUM_COUNTRY_BLUES = 109;
  GENRE_ENUM_COUNTRY_GOSPEL = 110;
  GENRE_ENUM_COUNTRY_ROCK = 111;
  GENRE_ENUM_COWPUNK = 112;
  GENRE_ENUM_CROSSOVER_THRASH = 113;
  GENRE_ENUM_CRUNK = 114;
  GENRE_ENUM_CRUST_PUNK = 115;
  GENRE_ENUM_CUMBIA = 116;
  GENRE_ENUM_DANCE_PUNK = 117;
  GENRE_ENUM_DANCE_POP = 118;
  GENRE_ENUM_DANCE_ROCK = 119;
  GENRE_ENUM_DANCEHALL = 120;
  GENRE_ENUM_DANGDUT = 121;
  GENRE_ENUM_DARK_AMBIENT = 122;
  GENRE_ENUM_DARK_WAVE = 123;
  GENRE_ENUM_DEATH_CORE = 124;
  GENRE_ENUM_DEATH_METAL = 125;
  GENRE_ENUM_DEATHGRIND = 126;
  GENRE_ENUM_DEEP_HOUSE = 127;
  GENRE_ENUM_DELTA_BLUES = 128;
  GENRE_ENUM_DESI = 129;
  GENRE_ENUM_DETROIT_TECHNO = 130;
  GENRE_ENUM_DIGITAL_HARDCORE = 131;
  GENRE_ENUM_DIRTY_SOUTH_RAP = 132;
  GENRE_ENUM_DISCO = 133;
  GENRE_ENUM_DISCO_HOUSE = 134;
  GENRE_ENUM_DJ = 135;
  GENRE_ENUM_DJENT = 136;
  GENRE_ENUM_DOO_WOP = 137;
  GENRE_ENUM_DOOM_METAL = 138;
  GENRE_ENUM_DOWNTEMPO = 139;
  GENRE_ENUM_DRAMA_THEME_MUSIC = 140;
  GENRE_ENUM_DREAM_POP = 141;
  GENRE_ENUM_DRONE = 142;
  GENRE_ENUM_DRUM_AND_BASS = 143;
  GENRE_ENUM_DUB = 144;
  GENRE_ENUM_DUB_TECHNO = 145;
  GENRE_ENUM_DUBSTEP = 146;
  GENRE_ENUM_DUTCH_ROCK = 147  [deprecated = true];
  GENRE_ENUM_EARLY_MUSIC = 148;
  GENRE_ENUM_EARWORM_SONG = 149;
  GENRE_ENUM_EAST_COAST_HIP_HOP = 150;
  GENRE_ENUM_EASY_LISTENING = 151;
  GENRE_ENUM_EBM = 152;
  GENRE_ENUM_ECLECTIC = 153;
  GENRE_ENUM_ELECTRIC_BLUES = 154;
  GENRE_ENUM_ELECTRO = 155;
  GENRE_ENUM_ELECTRO_INDUSTRIAL = 156;
  GENRE_ENUM_ELECTRO_SWING = 157;
  GENRE_ENUM_ELECTROCLASH = 158;
  GENRE_ENUM_ELECTRONIC = 159;
  GENRE_ENUM_EMO = 160;
  GENRE_ENUM_ENDING_MUSIC = 161;
  GENRE_ENUM_ENGLISH_LANGUAGE = 162  [deprecated = true];
  GENRE_ENUM_ENKA = 163;
  GENRE_ENUM_ENTERTAINMENT = 164;
  GENRE_ENUM_ETHEREAL_WAVE = 165;
  GENRE_ENUM_EUROBEAT = 166;
  GENRE_ENUM_EURODANCE = 167;
  GENRE_ENUM_EUROPE_LANGUAGE = 168  [deprecated = true];
  GENRE_ENUM_EUROPOP = 169;
  GENRE_ENUM_EXOTICA = 170;
  GENRE_ENUM_EXPERIMENTAL = 171;
  GENRE_ENUM_EXPERIMENTAL_ROCK = 172;
  GENRE_ENUM_FADO = 173;
  GENRE_ENUM_FEMALE_VOICE = 174;
  GENRE_ENUM_FILMI = 175;
  GENRE_ENUM_FLAMENCO = 176;
  GENRE_ENUM_FOLK = 177;
  GENRE_ENUM_FOLK_POP = 178;
  GENRE_ENUM_FOLK_METAL = 179;
  GENRE_ENUM_FOLK_PUNK = 180;
  GENRE_ENUM_FOLK_ROCK = 181;
  GENRE_ENUM_FORRO = 182;
  GENRE_ENUM_FREAK_FOLK = 183;
  GENRE_ENUM_FREAKBEAT = 184;
  GENRE_ENUM_FREE_IMPROVISATION = 185;
  GENRE_ENUM_FREE_JAZZ = 186;
  GENRE_ENUM_FREESTYLE = 187;
  GENRE_ENUM_FRENCH_LANGUAGE = 188  [deprecated = true];
  GENRE_ENUM_FREVO = 189;
  GENRE_ENUM_FUNERAL_DOOM = 190;
  GENRE_ENUM_FUNK = 191;
  GENRE_ENUM_FUNK_METAL = 192;
  GENRE_ENUM_FUNK_ROCK = 193;
  GENRE_ENUM_FUTUREPOP = 194;
  GENRE_ENUM_G_FUNK = 195;
  GENRE_ENUM_GABBA = 196;
  GENRE_ENUM_GAMELAN = 197;
  GENRE_ENUM_GANGSTER_RAP = 198;
  GENRE_ENUM_GARAGE_ROCK = 199;
  GENRE_ENUM_GERMAN_POP = 200  [deprecated = true];
  GENRE_ENUM_GHAZAL = 201;
  GENRE_ENUM_GLAM_METAL = 202;
  GENRE_ENUM_GLAM_ROCK = 203;
  GENRE_ENUM_GLITCH = 204;
  GENRE_ENUM_GOREGRIND = 205;
  GENRE_ENUM_GOSPEL = 206;
  GENRE_ENUM_GOTHIC_METAL = 207;
  GENRE_ENUM_GOTHIC_ROCK = 208;
  GENRE_ENUM_GOTHIC_SYMPHONIC_METAL = 209;
  GENRE_ENUM_GRAVE_WAVE = 210;
  GENRE_ENUM_GRIME = 211;
  GENRE_ENUM_GRINDCORE = 212;
  GENRE_ENUM_GROOVE_METAL = 213;
  GENRE_ENUM_GRUNGE = 214;
  GENRE_ENUM_GYPSY_JAZZ = 215;
  GENRE_ENUM_HAPPY_HARDCORE = 216;
  GENRE_ENUM_HARD_BOP = 217;
  GENRE_ENUM_HARD_HOUSE = 218;
  GENRE_ENUM_HARD_ROCK = 219;
  GENRE_ENUM_HARD_TRANCE = 220;
  GENRE_ENUM_HARDCORE = 221;
  GENRE_ENUM_HARDCORE_HIP_HOP = 222;
  GENRE_ENUM_HARDCORE_TECHNO = 223;
  GENRE_ENUM_HARDSTYLE = 224;
  GENRE_ENUM_HARMONICA_BLUES = 225;
  GENRE_ENUM_HAWAIIAN = 226  [deprecated = true];
  GENRE_ENUM_HI_NRG = 227;
  GENRE_ENUM_HIGHLIFE = 228;
  GENRE_ENUM_HIP_HOP = 229;
  GENRE_ENUM_HIP_HOUSE = 230;
  GENRE_ENUM_HIPLIFE = 231;
  GENRE_ENUM_HOKKIEN = 232;
  GENRE_ENUM_HORROR_PUNK = 233;
  GENRE_ENUM_HOUSE = 234;
  GENRE_ENUM_HUNGARIAN_POP = 235  [deprecated = true];
  GENRE_ENUM_HYPHY = 236;
  GENRE_ENUM_ICELANDIC_POP = 237  [deprecated = true];
  GENRE_ENUM_ILLBIENT = 238;
  GENRE_ENUM_INDIAN_CLASSICAL = 239  [deprecated = true];
  GENRE_ENUM_INDIAN_POP = 240  [deprecated = true];
  GENRE_ENUM_INDIE_FOLK = 241;
  GENRE_ENUM_INDIE_POP = 242;
  GENRE_ENUM_INDIE_ROCK = 243;
  GENRE_ENUM_INDIETRONICA = 244;
  GENRE_ENUM_INDONESIAN_POP = 245 [deprecated = true];
  GENRE_ENUM_INDUSTRIAL = 246;
  GENRE_ENUM_INDUSTRIAL_METAL = 247;
  GENRE_ENUM_INDUSTRIAL_ROCK = 248;
  GENRE_ENUM_INSPIRATIONAL = 249;
  GENRE_ENUM_INSTRUMENT = 250;
  GENRE_ENUM_INTELLIGENT_DANCE_MUSIC = 251;
  GENRE_ENUM_INTERLUDE = 252;
  GENRE_ENUM_IRISH_FOLK = 253  [deprecated = true];
  GENRE_ENUM_ITALIAN_DISCO = 254  [deprecated = true];
  GENRE_ENUM_J_POP = 255;
  GENRE_ENUM_J_ROCK = 256;
  GENRE_ENUM_JAM_BAND = 257;
  GENRE_ENUM_JANGLE_POP = 258;
  GENRE_ENUM_JAPANESE_LANGUAGE = 259  [deprecated = true];
  GENRE_ENUM_JAPANESE_PSYCHEDELIC = 260  [deprecated = true];
  GENRE_ENUM_JAPANOISE = 261;
  GENRE_ENUM_JAZZ = 262;
  GENRE_ENUM_JAZZ_BLUES = 263;
  GENRE_ENUM_JAZZ_FUNK = 264;
  GENRE_ENUM_JAZZ_FUSION = 265;
  GENRE_ENUM_JUDAICA = 266;
  GENRE_ENUM_JUG_BAND = 267;
  GENRE_ENUM_JUGGALO = 268;
  GENRE_ENUM_JUMP_BLUES = 269;
  GENRE_ENUM_JUNGLE_MUSIC = 270;
  GENRE_ENUM_K_POP = 271;
  GENRE_ENUM_KIWI_ROCK = 272;
  GENRE_ENUM_KIZOMBA = 273;
  GENRE_ENUM_KLEZMER = 274;
  GENRE_ENUM_KOMPA = 275;
  GENRE_ENUM_KOREAN_LANGUAGE = 276  [deprecated = true];
  GENRE_ENUM_KRAUT_ROCK = 277;
  GENRE_ENUM_KUDURO = 278;
  GENRE_ENUM_KWAITO = 279;
  GENRE_ENUM_LAIKO = 280;
  GENRE_ENUM_LATIN = 281;
  GENRE_ENUM_LATIN_ALTERNATIVE = 282;
  GENRE_ENUM_LATIN_JAZZ = 283;
  GENRE_ENUM_LATIN_POP = 284;
  GENRE_ENUM_LATIN_ROCK = 285;
  GENRE_ENUM_LIVE = 286;
  GENRE_ENUM_LIVE_MUSIC = 287;
  GENRE_ENUM_LO_FI = 288;
  GENRE_ENUM_LOCAL = 289;
  GENRE_ENUM_LOUISIANA_BLUES = 290;
  GENRE_ENUM_LOUNGE = 291;
  GENRE_ENUM_LOVE_SONGS = 292;
  GENRE_ENUM_LOVERS_ROCK = 293;
  GENRE_ENUM_MADCHESTER = 294;
  GENRE_ENUM_MALAYSIAN_POP = 295  [deprecated = true];
  GENRE_ENUM_MAMBO = 296;
  GENRE_ENUM_MANDARIN_LANGUAGE = 297 [deprecated = true];
  GENRE_ENUM_MARCHING_BAND = 298;
  GENRE_ENUM_MARIACHI = 299;
  GENRE_ENUM_MARTIAL_INDUSTRIAL = 300;
  GENRE_ENUM_MATH_ROCK = 301;
  GENRE_ENUM_MATHCORE = 302;
  GENRE_ENUM_MBALAX = 303;
  GENRE_ENUM_MEDIEVAL = 304;
  GENRE_ENUM_MELLOW_GOLD = 305;
  GENRE_ENUM_MELODIC_DEATH_METAL = 306;
  GENRE_ENUM_MELODIC_HARDCORE = 307;
  GENRE_ENUM_MELODIC_METALCORE = 308;
  GENRE_ENUM_MEMPHIS_BLUES = 309;
  GENRE_ENUM_MEMPHIS_SOUL = 310;
  GENRE_ENUM_MERENGUE = 311;
  GENRE_ENUM_MERSEYBEAT = 312;
  GENRE_ENUM_METAL = 313;
  GENRE_ENUM_METALCORE = 314;
  GENRE_ENUM_MEXICAN_SON = 315;
  GENRE_ENUM_MICROHOUSE = 316;
  GENRE_ENUM_MINIMAL = 317;
  GENRE_ENUM_MODERN_BLUES = 318;
  GENRE_ENUM_MODERN_CLASSICAL = 319;
  GENRE_ENUM_MOOMBAHTON = 320;
  GENRE_ENUM_MOTOWN = 321;
  GENRE_ENUM_MPB = 322;
  GENRE_ENUM_MUSIC = 323;
  GENRE_ENUM_MUSIC_FESTIVALS = 324;
  GENRE_ENUM_MUSIQUE_CONCRETE = 325;
  GENRE_ENUM_NASHVILLE_SOUND = 326;
  GENRE_ENUM_NATIVE_AMERICAN = 327;
  GENRE_ENUM_NEO_PROGRESSIVE = 328;
  GENRE_ENUM_NEO_CLASSICAL_METAL = 329;
  GENRE_ENUM_NEO_SOUL = 330;
  GENRE_ENUM_NEOCLASSICAL = 331;
  GENRE_ENUM_NEOFOLK = 332;
  GENRE_ENUM_NEUE_DEUTSCHE_HARTE = 333;
  GENRE_ENUM_NEUE_DEUTSCHE_WELLE = 334;
  GENRE_ENUM_NEW_AGE = 335;
  GENRE_ENUM_NEW_BEAT = 336;
  GENRE_ENUM_NEW_CENTURY = 337;
  GENRE_ENUM_NEW_JACK_SWING = 338;
  GENRE_ENUM_NEW_ORLEANS_BLUES = 339;
  GENRE_ENUM_NEW_ORLEANS_JAZZ = 340;
  GENRE_ENUM_NEW_RAVE = 341;
  GENRE_ENUM_NEW_WAVE = 342;
  GENRE_ENUM_NEW_WEIRD_AMERICA = 343;
  GENRE_ENUM_NEWS = 344;
  GENRE_ENUM_NINJA = 345;
  GENRE_ENUM_NO_WAVE = 346;
  GENRE_ENUM_NOISE_POP = 347;
  GENRE_ENUM_NOISE_ROCK = 348;
  GENRE_ENUM_NORTHERN_SOUL = 349;
  GENRE_ENUM_NU_JAZZ = 350;
  GENRE_ENUM_NU_METAL = 351;
  GENRE_ENUM_NU_SKOOL_BREAKS = 352;
  GENRE_ENUM_NWOBHM = 353;
  GENRE_ENUM_OI = 354;
  GENRE_ENUM_OKINAWAN_FOLK = 355;
  GENRE_ENUM_OLD_TIME = 356;
  GENRE_ENUM_OLD_SCHOOL_HIP_HOP = 357;
  GENRE_ENUM_OPENING_MUSIC = 358;
  GENRE_ENUM_OPERA = 359;
  GENRE_ENUM_OPM = 360;
  GENRE_ENUM_ORATORY = 361;
  GENRE_ENUM_OUTLAW_COUNTRY = 362;
  GENRE_ENUM_PAGAN_BLACK_METAL = 363;
  GENRE_ENUM_PAGODE = 364;
  GENRE_ENUM_PIANO = 365;
  GENRE_ENUM_PIANO_BLUES = 366;
  GENRE_ENUM_PIANO_ROCK = 367;
  GENRE_ENUM_PIEDMONT_BLUES = 368;
  GENRE_ENUM_PODCAST = 369;
  GENRE_ENUM_POLKA = 370;
  GENRE_ENUM_POP = 371;
  GENRE_ENUM_POP_PUNK = 372;
  GENRE_ENUM_POP_RAP = 373;
  GENRE_ENUM_POP_ROCK = 374;
  GENRE_ENUM_PORTUGUESE_ROCK = 375  [deprecated = true];
  GENRE_ENUM_POST_DISCO = 376;
  GENRE_ENUM_POST_GRUNGE = 377;
  GENRE_ENUM_POST_HARDCORE = 378;
  GENRE_ENUM_POST_METAL = 379;
  GENRE_ENUM_POST_PUNK = 380;
  GENRE_ENUM_POST_ROCK = 381;
  GENRE_ENUM_POWER_ELECTRONICS = 382;
  GENRE_ENUM_POWER_METAL = 383;
  GENRE_ENUM_POWER_NOISE = 384;
  GENRE_ENUM_POWER_POP = 385;
  GENRE_ENUM_POWER_VIOLENCE = 386;
  GENRE_ENUM_PROGRESSIVE_BLUEGRASS = 387;
  GENRE_ENUM_PROGRESSIVE_HOUSE = 388;
  GENRE_ENUM_PROGRESSIVE_METAL = 389;
  GENRE_ENUM_PROGRESSIVE_ROCK = 390;
  GENRE_ENUM_PROGRESSIVE_TRANCE = 391;
  GENRE_ENUM_PROTOPUNK = 392;
  GENRE_ENUM_PSYCHEDELIC_ROCK = 393;
  GENRE_ENUM_PSYCHEDELIC_TRANCE = 394;
  GENRE_ENUM_PSYCHOBILLY = 395;
  GENRE_ENUM_PUBLIC = 396;
  GENRE_ENUM_PUNK = 397;
  GENRE_ENUM_PUNK_BLUES = 398;
  GENRE_ENUM_PURE_MUSIC = 399;
  GENRE_ENUM_QAWWALI = 400;
  GENRE_ENUM_QUIET_STORM = 401;
  GENRE_ENUM_R_AND_B = 402;
  GENRE_ENUM_RAGTIME = 403;
  GENRE_ENUM_RAI = 404;
  GENRE_ENUM_RANCHERA = 405;
  GENRE_ENUM_RAP = 406;
  GENRE_ENUM_RAP_METAL = 407;
  GENRE_ENUM_RAP_ROCK = 408;
  GENRE_ENUM_REGGAE = 409;
  GENRE_ENUM_REGGAETON = 410;
  GENRE_ENUM_RELIGIOUS = 411;
  GENRE_ENUM_RENAISSANCE = 412;
  GENRE_ENUM_RHYTHM = 413;
  GENRE_ENUM_RIOT_GRRRL = 414;
  GENRE_ENUM_ROCK = 415;
  GENRE_ENUM_ROCK_EN_ESPANOL = 416  [deprecated = true];
  GENRE_ENUM_ROCK_N_ROLL = 417;
  GENRE_ENUM_ROCK_STEADY = 418;
  GENRE_ENUM_ROCKABILLY = 419;
  GENRE_ENUM_ROOTS_REGGAE = 420;
  GENRE_ENUM_ROOTS_ROCK = 421;
  GENRE_ENUM_RUMBA = 422;
  GENRE_ENUM_RUSSIAN_POP = 423  [deprecated = true];
  GENRE_ENUM_RUSSIAN_ROCK = 424  [deprecated = true];
  GENRE_ENUM_SALSA = 425;
  GENRE_ENUM_SAMBA = 426;
  GENRE_ENUM_SCHLAGER = 427;
  GENRE_ENUM_SCREAMO = 428;
  GENRE_ENUM_SERIALISM = 429;
  GENRE_ENUM_SERTANEJO = 430;
  GENRE_ENUM_SEXY = 431;
  GENRE_ENUM_SHIBUYA_KEI = 432;
  GENRE_ENUM_SHOEGAZE = 433;
  GENRE_ENUM_SHOW_TUNES = 434;
  GENRE_ENUM_SINGER_SONGWRITER = 435;
  GENRE_ENUM_SKA = 436;
  GENRE_ENUM_SKA_PUNK = 437;
  GENRE_ENUM_SKATE_PUNK = 438;
  GENRE_ENUM_SKIFFLE = 439;
  GENRE_ENUM_SKWEEE = 440;
  GENRE_ENUM_SLOVENIAN_ROCK = 441  [deprecated = true];
  GENRE_ENUM_SLOW_CORE = 442;
  GENRE_ENUM_SLOW_PACE = 443;
  GENRE_ENUM_SLUDGE_METAL = 444;
  GENRE_ENUM_SMOOTH_JAZZ = 445;
  GENRE_ENUM_SOCA = 446;
  GENRE_ENUM_SOFT_ROCK = 447;
  GENRE_ENUM_SOUKOUS = 448;
  GENRE_ENUM_SOUL = 449;
  GENRE_ENUM_SOUL_BLUES = 450;
  GENRE_ENUM_SOUL_JAZZ = 451;
  GENRE_ENUM_SOUNDTRACK = 452;
  GENRE_ENUM_SOUTHERN_GOSPEL = 453;
  GENRE_ENUM_SOUTHERN_HIP_HOP = 454;
  GENRE_ENUM_SOUTHERN_ROCK = 455;
  GENRE_ENUM_SOUTHERN_SOUL = 456;
  GENRE_ENUM_SPACE_ROCK = 457;
  GENRE_ENUM_SPANISH_MUSIC = 458  [deprecated = true];
  GENRE_ENUM_SPECIALITY = 459;
  GENRE_ENUM_SPEED_GARAGE = 460;
  GENRE_ENUM_SPEED_METAL = 461;
  GENRE_ENUM_SPEEDCORE = 462;
  GENRE_ENUM_SPOKEN_AUDIO = 463;
  GENRE_ENUM_SPORTS = 464;
  GENRE_ENUM_SPORTS_NEWS = 465;
  GENRE_ENUM_STEAMPUNK = 466;
  GENRE_ENUM_STONER_METAL = 467;
  GENRE_ENUM_STONER_ROCK = 468;
  GENRE_ENUM_STRAIGHT_EDGE = 469;
  GENRE_ENUM_STRIDE = 470;
  GENRE_ENUM_STRING_QUARTET = 471;
  GENRE_ENUM_SUFI = 472;
  GENRE_ENUM_SUOMI_ROCK = 473;
  GENRE_ENUM_SURF_MUSIC = 474;
  GENRE_ENUM_SWAMP_BLUES = 475;
  GENRE_ENUM_SWEDISH_INDIE_POP = 476  [deprecated = true];
  GENRE_ENUM_SWING = 477;
  GENRE_ENUM_SYMPHONIC_BLACK_METAL = 478;
  GENRE_ENUM_SYMPHONIC_METAL = 479;
  GENRE_ENUM_SYMPHONIC_ROCK = 480;
  GENRE_ENUM_SYNTHPOP = 481;
  GENRE_ENUM_TAIWANESE_POP = 482  [deprecated = true];
  GENRE_ENUM_TALK = 483;
  GENRE_ENUM_TANGO = 484;
  GENRE_ENUM_TECH_HOUSE = 485;
  GENRE_ENUM_TECHNICAL_DEATH_METAL = 486;
  GENRE_ENUM_TECHNO = 487;
  GENRE_ENUM_TEEN_POP = 488;
  GENRE_ENUM_TEJANO = 489;
  GENRE_ENUM_TEKNO = 490;
  GENRE_ENUM_TEXAS_BLUES = 491;
  GENRE_ENUM_TEXAS_COUNTRY = 492;
  GENRE_ENUM_THAI_POP = 493[deprecated = true];
  GENRE_ENUM_THEME_MUSIC = 494;
  GENRE_ENUM_THRASH_CORE = 495;
  GENRE_ENUM_THRASH_METAL = 496;
  GENRE_ENUM_THROAT_SINGING = 497;
  GENRE_ENUM_TIN_PAN_ALLEY = 498;
  GENRE_ENUM_TOP_40 = 499;
  GENRE_ENUM_TRADITIONAL_BLUES = 500;
  GENRE_ENUM_TRADITIONAL_COUNTRY = 501;
  GENRE_ENUM_TRADITIONAL_FOLK = 502;
  GENRE_ENUM_TRANCE = 503;
  GENRE_ENUM_TRAP_MUSIC = 504;
  GENRE_ENUM_TRAPSTEP = 505;
  GENRE_ENUM_TRIBAL_HOUSE = 506;
  GENRE_ENUM_TRIP_HOP = 507;
  GENRE_ENUM_TURBO_FOLK = 508;
  GENRE_ENUM_TURNTABLISM = 509;
  GENRE_ENUM_TWEE_POP = 510;
  GENRE_ENUM_UK_GARAGE = 511;
  GENRE_ENUM_UK_POST_PUNK = 512;
  GENRE_ENUM_UNDERGROUND_HIP_HOP = 513;
  GENRE_ENUM_UPLIFTING_TRANCE = 514;
  GENRE_ENUM_URBAN_CONTEMPORARY = 515;
  GENRE_ENUM_VALLENATO = 516;
  GENRE_ENUM_VAPORWAVE = 517;
  GENRE_ENUM_VARIETY = 518;
  GENRE_ENUM_VIDEO_GAME_MUSIC = 519;
  GENRE_ENUM_VIKING_METAL = 520;
  GENRE_ENUM_VISUAL_KEI = 521;
  GENRE_ENUM_VOCAL_HOUSE = 522;
  GENRE_ENUM_VOCAL_JAZZ = 523;
  GENRE_ENUM_WARM_DRONE = 524;
  GENRE_ENUM_WEATHER = 525;
  GENRE_ENUM_WEST_COAST_RAP = 526;
  GENRE_ENUM_WESTERN_LANGUAGE = 527  [deprecated = true];
  GENRE_ENUM_WESTERN_SWING = 528;
  GENRE_ENUM_WIND_ENSEMBLE = 529;
  GENRE_ENUM_WORLD_CLASSIC = 530;
  GENRE_ENUM_WORLD_MUSIC = 531;
  GENRE_ENUM_WORSHIP = 532;
  GENRE_ENUM_YOUTH = 533;
  GENRE_ENUM_ZOUK = 534;
  GENRE_ENUM_ZYDECO = 535;
}