// Copyright © 2022 Cerence Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the “Software”),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

syntax = "proto3";

package cerence.cloudservices.domain.common.content.media.v1;

import "cerence/cloudservices/domain/common/content/media/v1/visual_content.proto";

option go_package = "cerence/cloudservices/domain/common/content/media/v1";
option java_multiple_files = true;
option java_outer_classname = "ReleaseDateProto";
option java_package = "com.cerence.cloudservices.domain.common.content.media.v1";


message ReleaseDate{
  ReleaseDateEnum release_date=1;

  string relese_date_name=3;

  repeated VisualContent media=4;
}

enum ReleaseDateEnum{
  RELEASE_DATE_ENUM_UNSPECIFIED = 0;
  RELEASE_DATE_ENUM_1900 = 1;
  RELEASE_DATE_ENUM_1900_1909 = 2;
  RELEASE_DATE_ENUM_1901 = 3;
  RELEASE_DATE_ENUM_1902 = 4;
  RELEASE_DATE_ENUM_1903 = 5;
  RELEASE_DATE_ENUM_1904 = 6;
  RELEASE_DATE_ENUM_1905 = 7;
  RELEASE_DATE_ENUM_1906 = 8;
  RELEASE_DATE_ENUM_1907 = 9;
  RELEASE_DATE_ENUM_1908 = 10;
  RELEASE_DATE_ENUM_1909 = 11;
  RELEASE_DATE_ENUM_1910 = 12;
  RELEASE_DATE_ENUM_1910_1919 = 13;
  RELEASE_DATE_ENUM_1911 = 14;
  RELEASE_DATE_ENUM_1912 = 15;
  RELEASE_DATE_ENUM_1913 = 16;
  RELEASE_DATE_ENUM_1914 = 17;
  RELEASE_DATE_ENUM_1915 = 18;
  RELEASE_DATE_ENUM_1916 = 19;
  RELEASE_DATE_ENUM_1917 = 20;
  RELEASE_DATE_ENUM_1918 = 21;
  RELEASE_DATE_ENUM_1919 = 22;
  RELEASE_DATE_ENUM_1920 = 23;
  RELEASE_DATE_ENUM_1920_1929  = 24;
  RELEASE_DATE_ENUM_1921 = 25;
  RELEASE_DATE_ENUM_1922 = 26;
  RELEASE_DATE_ENUM_1923 = 27;
  RELEASE_DATE_ENUM_1924 = 28;
  RELEASE_DATE_ENUM_1925 = 29;
  RELEASE_DATE_ENUM_1926 = 30;
  RELEASE_DATE_ENUM_1927 = 31;
  RELEASE_DATE_ENUM_1928 = 32;
  RELEASE_DATE_ENUM_1929 = 33;
  RELEASE_DATE_ENUM_1930 = 34;
  RELEASE_DATE_ENUM_1930_1939 = 35;
  RELEASE_DATE_ENUM_1931 = 36;
  RELEASE_DATE_ENUM_1932 = 37;
  RELEASE_DATE_ENUM_1933 = 38;
  RELEASE_DATE_ENUM_1934 = 39;
  RELEASE_DATE_ENUM_1935 = 40;
  RELEASE_DATE_ENUM_1936 = 41;
  RELEASE_DATE_ENUM_1937 = 42;
  RELEASE_DATE_ENUM_1938 = 43;
  RELEASE_DATE_ENUM_1939 = 44;
  RELEASE_DATE_ENUM_1940 = 45;
  RELEASE_DATE_ENUM_1940_1949 = 46;
  RELEASE_DATE_ENUM_1941 = 47;
  RELEASE_DATE_ENUM_1942 = 48;
  RELEASE_DATE_ENUM_1943 = 49;
  RELEASE_DATE_ENUM_1944 = 50;
  RELEASE_DATE_ENUM_1945 = 51;
  RELEASE_DATE_ENUM_1946 = 52;
  RELEASE_DATE_ENUM_1947 = 53;
  RELEASE_DATE_ENUM_1948 = 54;
  RELEASE_DATE_ENUM_1949 = 55;
  RELEASE_DATE_ENUM_1950 = 56;
  RELEASE_DATE_ENUM_1950_1959 = 57;
  RELEASE_DATE_ENUM_1951 = 58;
  RELEASE_DATE_ENUM_1952 = 59;
  RELEASE_DATE_ENUM_1953 = 60;
  RELEASE_DATE_ENUM_1954 = 61;
  RELEASE_DATE_ENUM_1955 = 62;
  RELEASE_DATE_ENUM_1956 = 63;
  RELEASE_DATE_ENUM_1957 = 64;
  RELEASE_DATE_ENUM_1958 = 65;
  RELEASE_DATE_ENUM_1959 = 66;
  RELEASE_DATE_ENUM_1960 = 67;
  RELEASE_DATE_ENUM_1960_1969 = 68;
  RELEASE_DATE_ENUM_1961 = 69;
  RELEASE_DATE_ENUM_1962 = 70;
  RELEASE_DATE_ENUM_1963 = 71;
  RELEASE_DATE_ENUM_1964 = 72;
  RELEASE_DATE_ENUM_1965 = 73;
  RELEASE_DATE_ENUM_1966 = 74;
  RELEASE_DATE_ENUM_1967 = 75;
  RELEASE_DATE_ENUM_1968 = 76;
  RELEASE_DATE_ENUM_1969 = 77;
  RELEASE_DATE_ENUM_1970 = 78;
  RELEASE_DATE_ENUM_1970_1979 = 79;
  RELEASE_DATE_ENUM_1971 = 80;
  RELEASE_DATE_ENUM_1972 = 81;
  RELEASE_DATE_ENUM_1973 = 82;
  RELEASE_DATE_ENUM_1974 = 83;
  RELEASE_DATE_ENUM_1975 = 84;
  RELEASE_DATE_ENUM_1976 = 85;
  RELEASE_DATE_ENUM_1977 = 86;
  RELEASE_DATE_ENUM_1978 = 87;
  RELEASE_DATE_ENUM_1979 = 88;
  RELEASE_DATE_ENUM_1980 = 89;
  RELEASE_DATE_ENUM_1980_1989 = 90;
  RELEASE_DATE_ENUM_1981 = 91;
  RELEASE_DATE_ENUM_1982 = 92;
  RELEASE_DATE_ENUM_1983 = 93;
  RELEASE_DATE_ENUM_1984 = 94;
  RELEASE_DATE_ENUM_1985 = 95;
  RELEASE_DATE_ENUM_1986 = 96;
  RELEASE_DATE_ENUM_1987 = 97;
  RELEASE_DATE_ENUM_1988 = 98;
  RELEASE_DATE_ENUM_1989 = 99;
  RELEASE_DATE_ENUM_1990 = 100;
  RELEASE_DATE_ENUM_1990_1999 = 101;
  RELEASE_DATE_ENUM_1991 = 102;
  RELEASE_DATE_ENUM_1992 = 103;
  RELEASE_DATE_ENUM_1993 = 104;
  RELEASE_DATE_ENUM_1994 = 105;
  RELEASE_DATE_ENUM_1995 = 106;
  RELEASE_DATE_ENUM_1996 = 107;
  RELEASE_DATE_ENUM_1997 = 108;
  RELEASE_DATE_ENUM_1998 = 109;
  RELEASE_DATE_ENUM_1999 = 110;
  RELEASE_DATE_ENUM_2000 = 111;
  RELEASE_DATE_ENUM_2000_2009 = 112;
  RELEASE_DATE_ENUM_2001 = 113;
  RELEASE_DATE_ENUM_2002 = 114;
  RELEASE_DATE_ENUM_2003 = 115;
  RELEASE_DATE_ENUM_2004 = 116;
  RELEASE_DATE_ENUM_2005 = 117;
  RELEASE_DATE_ENUM_2006 = 118;
  RELEASE_DATE_ENUM_2007 = 119;
  RELEASE_DATE_ENUM_2008 = 120;
  RELEASE_DATE_ENUM_2009 = 121;
  RELEASE_DATE_ENUM_2010 = 122;
  RELEASE_DATE_ENUM_2010_2019 = 123;
  RELEASE_DATE_ENUM_2011 = 124;
  RELEASE_DATE_ENUM_2012 = 125;
  RELEASE_DATE_ENUM_2013 = 126;
  RELEASE_DATE_ENUM_2014 = 127;
  RELEASE_DATE_ENUM_2015 = 128;
  RELEASE_DATE_ENUM_2016 = 129;
  RELEASE_DATE_ENUM_2017 = 130;
  RELEASE_DATE_ENUM_2018 = 131;
  RELEASE_DATE_ENUM_2019 = 132;
  RELEASE_DATE_ENUM_2020 = 133;
  RELEASE_DATE_ENUM_2020_2029 = 134;
  RELEASE_DATE_ENUM_2021 = 135;
  RELEASE_DATE_ENUM_2022 = 136;
  RELEASE_DATE_ENUM_2023 = 137;
  RELEASE_DATE_ENUM_2024 = 138;
  RELEASE_DATE_ENUM_2025 = 139;
  RELEASE_DATE_ENUM_LAST_YEAR = 140;
  RELEASE_DATE_ENUM_NEXT_YEAR = 141;
  RELEASE_DATE_ENUM_THIS_YEAR = 142;
  RELEASE_DATE_ENUM_YEAR_AFTER_NEXT = 143;
  RELEASE_DATE_ENUM_YEAR_BEFORE_LAST = 144;
}