// Copyright © 2022 Cerence Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the “Software”),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

syntax = "proto3";

package cerence.cloudservices.domain.common.content.media.v1;


option go_package = "cerence/cloudservices/domain/common/content/media/v1";
option java_multiple_files = true;
option java_outer_classname = "SiriusXMProto";
option java_package = "com.cerence.cloudservices.domain.common.content.media.v1";




message SiriusXMChannelMetadata{
  string guid=1;

  string short_description=2;

  string long_description=3;

  repeated int32 line_up=4;

  string streaming_name=5;

  string tune_method=6;
}

message SiriusXMShowMetadata{
  string guid=1;

  string short_title=2;

  string long_title=3;

  string long_description=4;

  repeated SiriusXMChannelMetadata channels=5;
}
