# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/services/tts/v1/tts_marker_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?cerence/cloudservices/api/services/tts/v1/tts_marker_type.proto\x12)cerence.cloudservices.api.services.tts.v1*\xc2\x01\n\rTtsMarkerType\x12\x1f\n\x1bTTS_MARKER_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n\x19TTS_MARKER_TYPE_PARAGRAPH\x10\x01\x12\x1c\n\x18TTS_MARKER_TYPE_SENTENCE\x10\x02\x12\x18\n\x14TTS_MARKER_TYPE_WORD\x10\x03\x12\x1b\n\x17TTS_MARKER_TYPE_PHONEME\x10\x04\x12\x1c\n\x18TTS_MARKER_TYPE_BOOKMARK\x10\x05\x42p\n-com.cerence.cloudservices.api.services.tts.v1B\x12TtsMarkerTypeProtoP\x01Z)cerence/cloudservices/api/services/tts/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.tts.v1.tts_marker_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.cerence.cloudservices.api.services.tts.v1B\022TtsMarkerTypeProtoP\001Z)cerence/cloudservices/api/services/tts/v1'
  _TTSMARKERTYPE._serialized_start=111
  _TTSMARKERTYPE._serialized_end=305
# @@protoc_insertion_point(module_scope)
