// Copyright © 2022 Cerence Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the “Software”),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

syntax = "proto3";

package cerence.cloudservices.domain.common.dialog.v1;


option go_package = "cerence/cloudservices/domain/common/dialog/v1";
option java_multiple_files = true;
option java_package = "com.cerence.cloudservices.domain.common.dialog.v1";
option java_outer_classname = "DialogQueryProto";

message QueryRequest {
  string task_id = 1;

  Query query = 2;
}


message Query {
  // The identifier from the query generated by the dialog.
  uint32 query_id = 1;

  // The name of the concept that should be queried by the client.
  string query_concept = 2;

  // The criteria
  Criteria criteria = 3;
}

message Criteria {
  // Array of concepts
  repeated Concept concepts = 1;
}

message Concept {
  string concept_name = 1;

  repeated ConceptItem items = 2;
}

message ConceptItem {
  string value = 1;

  string literal = 2;
}