# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/news/v1/news_entity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/news/v1/news_entity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEcerence/cloudservices/domain/common/content/news/v1/news_entity.proto\x12\x33\x63\x65rence.cloudservices.domain.common.content.news.v1\"\x8b\x03\n\nNewsEntity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08headline\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x15\n\rcomplete_text\x18\x04 \x01(\t\x12\x12\n\x06source\x18\x05 \x01(\tB\x02\x18\x01\x12\x14\n\x0c\x64\x61te_created\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61te_update\x18\x07 \x01(\t\x12\x10\n\x08priority\x18\x08 \x01(\t\x12\x10\n\x08language\x18\t \x01(\t\x12\x11\n\tgeography\x18\n \x01(\t\x12\x0e\n\x06\x61uthor\x18\x0b \x01(\t\x12\x11\n\timage_url\x18\x0c \x01(\t\x12\x12\n\ncategories\x18\r \x01(\t\x12\x11\n\tlocations\x18\x0e \x01(\t\x12\x11\n\taudio_url\x18\x0f \x01(\t\x12\x64\n\x13\x61ttribution_details\x18\x10 \x01(\x0b\x32G.cerence.cloudservices.domain.common.content.news.v1.AttributionDetails\"\xbb\x01\n\x12\x41ttributionDetails\x12R\n\tpublisher\x18\x01 \x01(\x0b\x32?.cerence.cloudservices.domain.common.content.news.v1.NewsSource\x12Q\n\x08provider\x18\x02 \x01(\x0b\x32?.cerence.cloudservices.domain.common.content.news.v1.NewsSource\"-\n\nNewsSource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\timage_url\x18\x02 \x01(\tB\x81\x01\n7com.cerence.cloudservices.domain.common.content.news.v1B\x0fNewsEntityProtoP\x01Z3cerence/cloudservices/domain/common/content/news/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.news.v1.news_entity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n7com.cerence.cloudservices.domain.common.content.news.v1B\017NewsEntityProtoP\001Z3cerence/cloudservices/domain/common/content/news/v1'
  _globals['_NEWSENTITY'].fields_by_name['source']._loaded_options = None
  _globals['_NEWSENTITY'].fields_by_name['source']._serialized_options = b'\030\001'
  _globals['_NEWSENTITY']._serialized_start=127
  _globals['_NEWSENTITY']._serialized_end=522
  _globals['_ATTRIBUTIONDETAILS']._serialized_start=525
  _globals['_ATTRIBUTIONDETAILS']._serialized_end=712
  _globals['_NEWSSOURCE']._serialized_start=714
  _globals['_NEWSSOURCE']._serialized_end=759
# @@protoc_insertion_point(module_scope)
