# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/news/v1/news_content.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/news/v1/news_content.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.news.v1 import news_entity_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_news_dot_v1_dot_news__entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcerence/cloudservices/domain/common/content/news/v1/news_content.proto\x12\x33\x63\x65rence.cloudservices.domain.common.content.news.v1\x1a\x45\x63\x65rence/cloudservices/domain/common/content/news/v1/news_entity.proto\"e\n\x0bNewsContent\x12V\n\rnews_entities\x18\x01 \x03(\x0b\x32?.cerence.cloudservices.domain.common.content.news.v1.NewsEntityB\x82\x01\n7com.cerence.cloudservices.domain.common.content.news.v1B\x10NewsContentProtoP\x01Z3cerence/cloudservices/domain/common/content/news/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.news.v1.news_content_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n7com.cerence.cloudservices.domain.common.content.news.v1B\020NewsContentProtoP\001Z3cerence/cloudservices/domain/common/content/news/v1'
  _globals['_NEWSCONTENT']._serialized_start=198
  _globals['_NEWSCONTENT']._serialized_end=299
# @@protoc_insertion_point(module_scope)
