# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/dialog/v1/dialog_query.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.api.dialog.v1 import dialog_candidate_pb2 as cerence_dot_cloudservices_dot_api_dot_dialog_dot_v1_dot_dialog__candidate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6cerence/cloudservices/api/dialog/v1/dialog_query.proto\x12#cerence.cloudservices.api.dialog.v1\x1a:cerence/cloudservices/api/dialog/v1/dialog_candidate.proto\"r\n\x11\x44ialogQueryAnswer\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12L\n\x0cquery_result\x18\x02 \x01(\x0b\x32\x36.cerence.cloudservices.api.dialog.v1.DialogQueryResult\"\x80\x01\n\x11\x44ialogQueryResult\x12\x10\n\x08query_id\x18\x01 \x01(\r\x12\x15\n\rquery_concept\x18\x02 \x01(\t\x12\x42\n\ncandidates\x18\x03 \x03(\x0b\x32..cerence.cloudservices.api.dialog.v1.CandidateBb\n\'com.cerence.cloudservices.api.dialog.v1B\x10\x44ialogQueryProtoP\x01Z#cerence/cloudservices/api/dialog/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.dialog.v1.dialog_query_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.cerence.cloudservices.api.dialog.v1B\020DialogQueryProtoP\001Z#cerence/cloudservices/api/dialog/v1'
  _DIALOGQUERYANSWER._serialized_start=155
  _DIALOGQUERYANSWER._serialized_end=269
  _DIALOGQUERYRESULT._serialized_start=272
  _DIALOGQUERYRESULT._serialized_end=400
# @@protoc_insertion_point(module_scope)
