# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/dialog/v1/dialog_candidate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:cerence/cloudservices/api/dialog/v1/dialog_candidate.proto\x12#cerence.cloudservices.api.dialog.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe0\x01\n\tCandidate\x12\x43\n\x05match\x18\x01 \x01(\x0e\x32\x34.cerence.cloudservices.api.dialog.v1.Candidate.Match\x12\x13\n\x0brelaxations\x18\x02 \x03(\t\x12%\n\x05value\x18\x03 \x01(\x0b\x32\x16.google.protobuf.Value\"R\n\x05Match\x12\x15\n\x11MATCH_UNSPECIFIED\x10\x00\x12\x0e\n\nMATCH_FULL\x10\x01\x12\x11\n\rMATCH_PARTIAL\x10\x02\x12\x0f\n\x0bMATCH_FUZZY\x10\x03\x42\x66\n\'com.cerence.cloudservices.api.dialog.v1B\x14\x44ialogCandidateProtoP\x01Z#cerence/cloudservices/api/dialog/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.dialog.v1.dialog_candidate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.cerence.cloudservices.api.dialog.v1B\024DialogCandidateProtoP\001Z#cerence/cloudservices/api/dialog/v1'
  _CANDIDATE._serialized_start=130
  _CANDIDATE._serialized_end=354
  _CANDIDATE_MATCH._serialized_start=272
  _CANDIDATE_MATCH._serialized_end=354
# @@protoc_insertion_point(module_scope)
