# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/dialog/v1/pnp_dialog_streaming_response_continuation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.api.common.v1 import interaction_history_pb2 as cerence_dot_cloudservices_dot_api_dot_common_dot_v1_dot_interaction__history__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nTcerence/cloudservices/api/dialog/v1/pnp_dialog_streaming_response_continuation.proto\x12#cerence.cloudservices.api.dialog.v1\x1a=cerence/cloudservices/api/common/v1/interaction_history.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc5\x02\n.PlugAndPlayDialogStreamingResponseContinuation\x12\x46\n\x0b\x66\x61\x63\x65t_chunk\x18\x01 \x01(\x0b\x32/.cerence.cloudservices.api.dialog.v1.FacetChunkH\x00\x12O\n\x10\x64ialog_follow_up\x18\x02 \x01(\x0b\x32\x33.cerence.cloudservices.api.dialog.v1.DialogFollowUpH\x00\x12T\n\x13interaction_history\x18\x03 \x01(\x0b\x32\x37.cerence.cloudservices.api.common.v1.InteractionHistory\x12\x14\n\x0csession_data\x18\x04 \x01(\x0c\x42\x0e\n\x0c\x63ontinuation\"\xcc\x01\n\nFacetChunk\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x03 \x01(\x0cH\x00\x12/\n\x0cstruct_value\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x12G\n\nchunk_info\x18\x05 \x01(\x0b\x32\x33.cerence.cloudservices.api.dialog.v1.FacetChunkInfoB\x07\n\x05value\"B\n\x0e\x46\x61\x63\x65tChunkInfo\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x05\x12\x1f\n\x17is_last_for_interaction\x18\x02 \x01(\x08\")\n\x0e\x44ialogFollowUp\x12\x17\n\x0fhas_active_task\x18\x01 \x01(\x08\x42\x85\x01\n\'com.cerence.cloudservices.api.dialog.v1B3PlugAndPlayDialogStreamingResponseContinuationProtoP\x01Z#cerence/cloudservices/api/dialog/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.dialog.v1.pnp_dialog_streaming_response_continuation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.cerence.cloudservices.api.dialog.v1B3PlugAndPlayDialogStreamingResponseContinuationProtoP\001Z#cerence/cloudservices/api/dialog/v1'
  _PLUGANDPLAYDIALOGSTREAMINGRESPONSECONTINUATION._serialized_start=219
  _PLUGANDPLAYDIALOGSTREAMINGRESPONSECONTINUATION._serialized_end=544
  _FACETCHUNK._serialized_start=547
  _FACETCHUNK._serialized_end=751
  _FACETCHUNKINFO._serialized_start=753
  _FACETCHUNKINFO._serialized_end=819
  _DIALOGFOLLOWUP._serialized_start=821
  _DIALOGFOLLOWUP._serialized_end=862
# @@protoc_insertion_point(module_scope)
