# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/services/asr/v1/asr_context.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.api.common.v1 import context_source_pb2 as cerence_dot_cloudservices_dot_api_dot_common_dot_v1_dot_context__source__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.type import latlng_pb2 as google_dot_type_dot_latlng__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;cerence/cloudservices/api/services/asr/v1/asr_context.proto\x12)cerence.cloudservices.api.services.asr.v1\x1a\x38\x63\x65rence/cloudservices/api/common/v1/context_source.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x18google/type/latlng.proto\"\xad\x01\n\x07\x43ontext\x12X\n\x12navigation_context\x18\x01 \x01(\x0b\x32<.cerence.cloudservices.api.services.asr.v1.NavigationContext\x12H\n\nui_context\x18\x02 \x01(\x0b\x32\x34.cerence.cloudservices.api.services.asr.v1.UIContext\"\x83\x02\n\x11NavigationContext\x12\x32\n\x10\x63urrent_location\x18\x01 \x01(\x0b\x32\x13.google.type.LatLngB\x03\xe0\x41\x02\x12Y\n\x17\x63urrent_location_source\x18\x02 \x01(\x0e\x32\x33.cerence.cloudservices.api.common.v1.LocationSourceB\x03\xe0\x41\x02\x12\x31\n\x14\x64\x65stination_location\x18\x03 \x01(\x0b\x32\x13.google.type.LatLng\x12,\n\x0ftarget_location\x18\x04 \x01(\x0b\x32\x13.google.type.LatLng\"\x9c\x01\n\tUIContext\x12/\n\x04text\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\x03\xe0\x41\x02\x12/\n\x05start\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueB\x03\xe0\x41\x02\x12-\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueB\x03\xe0\x41\x02\x42m\n-com.cerence.cloudservices.api.services.asr.v1B\x0f\x41srContextProtoP\x01Z)cerence/cloudservices/api/services/asr/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.asr.v1.asr_context_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.cerence.cloudservices.api.services.asr.v1B\017AsrContextProtoP\001Z)cerence/cloudservices/api/services/asr/v1'
  _NAVIGATIONCONTEXT.fields_by_name['current_location']._options = None
  _NAVIGATIONCONTEXT.fields_by_name['current_location']._serialized_options = b'\340A\002'
  _NAVIGATIONCONTEXT.fields_by_name['current_location_source']._options = None
  _NAVIGATIONCONTEXT.fields_by_name['current_location_source']._serialized_options = b'\340A\002'
  _UICONTEXT.fields_by_name['text']._options = None
  _UICONTEXT.fields_by_name['text']._serialized_options = b'\340A\002'
  _UICONTEXT.fields_by_name['start']._options = None
  _UICONTEXT.fields_by_name['start']._serialized_options = b'\340A\002'
  _UICONTEXT.fields_by_name['end']._options = None
  _UICONTEXT.fields_by_name['end']._serialized_options = b'\340A\002'
  _CONTEXT._serialized_start=256
  _CONTEXT._serialized_end=429
  _NAVIGATIONCONTEXT._serialized_start=432
  _NAVIGATIONCONTEXT._serialized_end=691
  _UICONTEXT._serialized_start=694
  _UICONTEXT._serialized_end=850
# @@protoc_insertion_point(module_scope)
