# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/services/asr/v1/spoken_form.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;cerence/cloudservices/api/services/asr/v1/spoken_form.proto\x12)cerence.cloudservices.api.services.asr.v1\x1a\x1fgoogle/api/field_behavior.proto\")\n\x0eWordSpokenForm\x12\x17\n\ntranscript\x18\x01 \x01(\tB\x03\xe0\x41\x02\x42m\n-com.cerence.cloudservices.api.services.asr.v1B\x0fSpokenFormProtoP\x01Z)cerence/cloudservices/api/services/asr/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.asr.v1.spoken_form_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.cerence.cloudservices.api.services.asr.v1B\017SpokenFormProtoP\001Z)cerence/cloudservices/api/services/asr/v1'
  _WORDSPOKENFORM.fields_by_name['transcript']._options = None
  _WORDSPOKENFORM.fields_by_name['transcript']._serialized_options = b'\340A\002'
  _WORDSPOKENFORM._serialized_start=139
  _WORDSPOKENFORM._serialized_end=180
# @@protoc_insertion_point(module_scope)
