# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/services/asr/v1/word_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9cerence/cloudservices/api/services/asr/v1/word_info.proto\x12)cerence.cloudservices.api.services.asr.v1\x1a\x1fgoogle/api/field_behavior.proto\"9\n\x08WordInfo\x12\x14\n\x07literal\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x17\n\nconfidence\x18\x02 \x01(\x02\x42\x03\xe0\x41\x02\x42k\n-com.cerence.cloudservices.api.services.asr.v1B\rWordInfoProtoP\x01Z)cerence/cloudservices/api/services/asr/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.asr.v1.word_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.cerence.cloudservices.api.services.asr.v1B\rWordInfoProtoP\001Z)cerence/cloudservices/api/services/asr/v1'
  _WORDINFO.fields_by_name['literal']._options = None
  _WORDINFO.fields_by_name['literal']._serialized_options = b'\340A\002'
  _WORDINFO.fields_by_name['confidence']._options = None
  _WORDINFO.fields_by_name['confidence']._serialized_options = b'\340A\002'
  _WORDINFO._serialized_start=137
  _WORDINFO._serialized_end=194
# @@protoc_insertion_point(module_scope)
