# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/common/v1/profanity_filter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:cerence/cloudservices/api/common/v1/profanity_filter.proto\x12#cerence.cloudservices.api.common.v1*p\n\x0fProfanityFilter\x12 \n\x1cPROFANITY_FILTER_UNSPECIFIED\x10\x00\x12\x1d\n\x19PROFANITY_FILTER_DISABLED\x10\x01\x12\x1c\n\x18PROFANITY_FILTER_ENABLED\x10\x02\x42\x66\n\'com.cerence.cloudservices.api.common.v1B\x14ProfanityFilterProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.profanity_filter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\024ProfanityFilterProtoP\001Z#cerence/cloudservices/api/common/v1'
  _PROFANITYFILTER._serialized_start=99
  _PROFANITYFILTER._serialized_end=211
# @@protoc_insertion_point(module_scope)
