# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/common/v1/query_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6cerence/cloudservices/api/common/v1/query_status.proto\x12#cerence.cloudservices.api.common.v1\"\x0e\n\x0cQueryStartedBb\n\'com.cerence.cloudservices.api.common.v1B\x10QueryStatusProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.query_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\020QueryStatusProtoP\001Z#cerence/cloudservices/api/common/v1'
  _QUERYSTARTED._serialized_start=95
  _QUERYSTARTED._serialized_end=109
# @@protoc_insertion_point(module_scope)
