# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/common/v1/route_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4cerence/cloudservices/api/common/v1/route_info.proto\x12#cerence.cloudservices.api.common.v1\x1a\x19google/protobuf/any.proto\"\x8e\x02\n\tRouteInfo\x12`\n\x19pipe_delimited_route_info\x18\x01 \x01(\x0b\x32;.cerence.cloudservices.api.common.v1.PipeDelimitedRouteInfoH\x00\x12\x64\n\x1bpolyline_encoded_route_info\x18\x02 \x01(\x0b\x32=.cerence.cloudservices.api.common.v1.PolylineEncodedRouteInfoH\x00\x12\x30\n\x12supplementary_info\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyB\x07\n\x05route\"\xae\x01\n\x16PipeDelimitedRouteInfo\x12G\n\x05route\x18\x01 \x01(\x0b\x32\x38.cerence.cloudservices.api.common.v1.PipeDelimitedPoints\x12K\n\tstopovers\x18\x02 \x01(\x0b\x32\x38.cerence.cloudservices.api.common.v1.PipeDelimitedPoints\"\xb4\x01\n\x18PolylineEncodedRouteInfo\x12I\n\x05route\x18\x01 \x01(\x0b\x32:.cerence.cloudservices.api.common.v1.PolylineEncodedPoints\x12M\n\tstopovers\x18\x02 \x01(\x0b\x32:.cerence.cloudservices.api.common.v1.PolylineEncodedPoints\"8\n\x15PolylineEncodedPoints\x12\x1f\n\x17polyline_encoded_points\x18\x01 \x01(\t\"4\n\x13PipeDelimitedPoints\x12\x1d\n\x15pipe_delimited_points\x18\x01 \x01(\tB`\n\'com.cerence.cloudservices.api.common.v1B\x0eRouteInfoProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.route_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\016RouteInfoProtoP\001Z#cerence/cloudservices/api/common/v1'
  _ROUTEINFO._serialized_start=121
  _ROUTEINFO._serialized_end=391
  _PIPEDELIMITEDROUTEINFO._serialized_start=394
  _PIPEDELIMITEDROUTEINFO._serialized_end=568
  _POLYLINEENCODEDROUTEINFO._serialized_start=571
  _POLYLINEENCODEDROUTEINFO._serialized_end=751
  _POLYLINEENCODEDPOINTS._serialized_start=753
  _POLYLINEENCODEDPOINTS._serialized_end=809
  _PIPEDELIMITEDPOINTS._serialized_start=811
  _PIPEDELIMITEDPOINTS._serialized_end=863
# @@protoc_insertion_point(module_scope)
