# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/context_media_details.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/context_media_details.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?cerence/cloudservices/api/common/v1/context_media_details.proto\x12#cerence.cloudservices.api.common.v1\"i\n\x0cMediaDetails\x12H\n\x0csong_details\x18\x01 \x01(\x0b\x32\x30.cerence.cloudservices.api.common.v1.SongDetailsH\x00\x42\x0f\n\rmedia_details\"e\n\x0bSongDetails\x12\x0f\n\x07\x61rtists\x18\x01 \x03(\t\x12\r\n\x05\x61lbum\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x18\n\x10\x64uration_seconds\x18\x05 \x01(\x05\x42\x62\n\'com.cerence.cloudservices.api.common.v1B\x10SongDetailsProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.context_media_details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\020SongDetailsProtoP\001Z#cerence/cloudservices/api/common/v1'
  _globals['_MEDIADETAILS']._serialized_start=104
  _globals['_MEDIADETAILS']._serialized_end=209
  _globals['_SONGDETAILS']._serialized_start=211
  _globals['_SONGDETAILS']._serialized_end=312
# @@protoc_insertion_point(module_scope)
