# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/feature_inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/feature_inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;cerence/cloudservices/api/common/v1/feature_inventory.proto\x12#cerence.cloudservices.api.common.v1\"a\n\x10\x46\x65\x61tureInventory\x12\x19\n\x11\x66\x65\x61ture_bundle_id\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\t\x12 \n\x18remaining_amount_summary\x18\x03 \x01(\x05\x42h\n\'com.cerence.cloudservices.api.common.v1B\x16\x46\x65\x61turesInventoryProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.feature_inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\026FeaturesInventoryProtoP\001Z#cerence/cloudservices/api/common/v1'
  _globals['_FEATUREINVENTORY']._serialized_start=100
  _globals['_FEATUREINVENTORY']._serialized_end=197
# @@protoc_insertion_point(module_scope)
