# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/personal_assistant_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/personal_assistant_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.api.common.v1 import personal_assistant_context_pb2 as cerence_dot_cloudservices_dot_api_dot_common_dot_v1_dot_personal__assistant__context__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcerence/cloudservices/api/common/v1/personal_assistant_request.proto\x12#cerence.cloudservices.api.common.v1\x1a\x44\x63\x65rence/cloudservices/api/common/v1/personal_assistant_context.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd0\x01\n\x18PersonalAssistantRequest\x12\x61\n\x1apersonal_assistant_context\x18\x01 \x01(\x0b\x32=.cerence.cloudservices.api.common.v1.PersonalAssistantContext\x12(\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06\x63ustom\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructBo\n\'com.cerence.cloudservices.api.common.v1B\x1dPersonalAssistantRequestProtoP\x00Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.personal_assistant_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\035PersonalAssistantRequestProtoP\000Z#cerence/cloudservices/api/common/v1'
  _globals['_PERSONALASSISTANTREQUEST']._serialized_start=210
  _globals['_PERSONALASSISTANTREQUEST']._serialized_end=418
# @@protoc_insertion_point(module_scope)
