# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/personal_assistant_context.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/personal_assistant_context.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcerence/cloudservices/api/common/v1/personal_assistant_context.proto\x12#cerence.cloudservices.api.common.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xde\x01\n\x18PersonalAssistantContext\x12N\n\x07session\x18\x01 \x01(\x0b\x32=.cerence.cloudservices.api.common.v1.PersonalAssistantSession\x12,\n\x0btransaction\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x44\n\x0b\x63lient_auth\x18\x03 \x03(\x0b\x32/.cerence.cloudservices.api.common.v1.ClientAuth\"\xe4\x01\n\x18PersonalAssistantSession\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\"\n\x1amulti_turn_dialog_no_pause\x18\x03 \x01(\x08\x12\x19\n\x11multi_turn_dialog\x18\x04 \x01(\x08\x12\"\n\x1amulti_turn_dialog_complete\x18\x05 \x01(\x08\x12\'\n\x1fmulti_turn_dialog_allows_rewind\x18\x06 \x01(\x08\x12\x19\n\x11\x63lient_time_stamp\x18\x07 \x01(\t\"E\n\nClientAuth\x12\x37\n\x04user\x18\x01 \x01(\x0b\x32).cerence.cloudservices.api.common.v1.User\"^\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nuser_token\x18\x02 \x01(\t\x12\x16\n\x0ethird_party_id\x18\x03 \x01(\t\x12\x19\n\x11third_party_token\x18\x04 \x01(\tBo\n\'com.cerence.cloudservices.api.common.v1B\x1dPersonalAssistantContextProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.personal_assistant_context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\035PersonalAssistantContextProtoP\001Z#cerence/cloudservices/api/common/v1'
  _globals['_PERSONALASSISTANTCONTEXT']._serialized_start=140
  _globals['_PERSONALASSISTANTCONTEXT']._serialized_end=362
  _globals['_PERSONALASSISTANTSESSION']._serialized_start=365
  _globals['_PERSONALASSISTANTSESSION']._serialized_end=593
  _globals['_CLIENTAUTH']._serialized_start=595
  _globals['_CLIENTAUTH']._serialized_end=664
  _globals['_USER']._serialized_start=666
  _globals['_USER']._serialized_end=760
# @@protoc_insertion_point(module_scope)
