# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/provider.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/provider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2cerence/cloudservices/api/common/v1/provider.proto\x12#cerence.cloudservices.api.common.v1*\xe9\x01\n\x11MediaProviderEnum\x12#\n\x1fMEDIA_PROVIDER_ENUM_UNSPECIFIED\x10\x00\x12!\n\x1dMEDIA_PROVIDER_ENUM_SIRIUS_XM\x10\x01\x12 \n\x1cMEDIA_PROVIDER_ENUM_STINGRAY\x10\x02\x12\x1f\n\x1bMEDIA_PROVIDER_ENUM_SPOTIFY\x10\x03\x12$\n MEDIA_PROVIDER_ENUM_AMAZON_MUSIC\x10\x04\x12#\n\x1fMEDIA_PROVIDER_ENUM_APPLE_MUSIC\x10\x05\x42_\n\'com.cerence.cloudservices.api.common.v1B\rProviderProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.provider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\rProviderProtoP\001Z#cerence/cloudservices/api/common/v1'
  _globals['_MEDIAPROVIDERENUM']._serialized_start=92
  _globals['_MEDIAPROVIDERENUM']._serialized_end=325
# @@protoc_insertion_point(module_scope)
