# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/response_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/response_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9cerence/cloudservices/api/common/v1/response_config.proto\x12#cerence.cloudservices.api.common.v1\x1a\x1egoogle/protobuf/wrappers.proto\"V\n\x0eResponseConfig\x12\x44\n enable_domain_response_streaming\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValueBe\n\'com.cerence.cloudservices.api.common.v1B\x13ResponseConfigProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.response_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\023ResponseConfigProtoP\001Z#cerence/cloudservices/api/common/v1'
  _globals['_RESPONSECONFIG']._serialized_start=130
  _globals['_RESPONSECONFIG']._serialized_end=216
# @@protoc_insertion_point(module_scope)
