# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/route_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/route_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from cerence.cloudservices.api.common.v1 import stopover_info_pb2 as cerence_dot_cloudservices_dot_api_dot_common_dot_v1_dot_stopover__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4cerence/cloudservices/api/common/v1/route_info.proto\x12#cerence.cloudservices.api.common.v1\x1a\x19google/protobuf/any.proto\x1a\x37\x63\x65rence/cloudservices/api/common/v1/stopover_info.proto\"\xd8\x02\n\tRouteInfo\x12`\n\x19pipe_delimited_route_info\x18\x01 \x01(\x0b\x32;.cerence.cloudservices.api.common.v1.PipeDelimitedRouteInfoH\x00\x12\x64\n\x1bpolyline_encoded_route_info\x18\x02 \x01(\x0b\x32=.cerence.cloudservices.api.common.v1.PolylineEncodedRouteInfoH\x00\x12H\n\rstopover_info\x18\x04 \x01(\x0b\x32\x31.cerence.cloudservices.api.common.v1.StopoverInfo\x12\x30\n\x12supplementary_info\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyB\x07\n\x05route\"\xae\x01\n\x16PipeDelimitedRouteInfo\x12G\n\x05route\x18\x01 \x01(\x0b\x32\x38.cerence.cloudservices.api.common.v1.PipeDelimitedPoints\x12K\n\tstopovers\x18\x02 \x01(\x0b\x32\x38.cerence.cloudservices.api.common.v1.PipeDelimitedPoints\"\xb4\x01\n\x18PolylineEncodedRouteInfo\x12I\n\x05route\x18\x01 \x01(\x0b\x32:.cerence.cloudservices.api.common.v1.PolylineEncodedPoints\x12M\n\tstopovers\x18\x02 \x01(\x0b\x32:.cerence.cloudservices.api.common.v1.PolylineEncodedPoints\"8\n\x15PolylineEncodedPoints\x12\x1f\n\x17polyline_encoded_points\x18\x01 \x01(\t\"4\n\x13PipeDelimitedPoints\x12\x1d\n\x15pipe_delimited_points\x18\x01 \x01(\tB`\n\'com.cerence.cloudservices.api.common.v1B\x0eRouteInfoProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.route_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\016RouteInfoProtoP\001Z#cerence/cloudservices/api/common/v1'
  _globals['_ROUTEINFO']._serialized_start=178
  _globals['_ROUTEINFO']._serialized_end=522
  _globals['_PIPEDELIMITEDROUTEINFO']._serialized_start=525
  _globals['_PIPEDELIMITEDROUTEINFO']._serialized_end=699
  _globals['_POLYLINEENCODEDROUTEINFO']._serialized_start=702
  _globals['_POLYLINEENCODEDROUTEINFO']._serialized_end=882
  _globals['_POLYLINEENCODEDPOINTS']._serialized_start=884
  _globals['_POLYLINEENCODEDPOINTS']._serialized_end=940
  _globals['_PIPEDELIMITEDPOINTS']._serialized_start=942
  _globals['_PIPEDELIMITEDPOINTS']._serialized_end=994
# @@protoc_insertion_point(module_scope)
