# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/voice_activation_mode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/voice_activation_mode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?cerence/cloudservices/api/common/v1/voice_activation_mode.proto\x12#cerence.cloudservices.api.common.v1*\xf6\x05\n\x13VoiceActivationMode\x12%\n!VOICE_ACTIVATION_MODE_UNSPECIFIED\x10\x00\x12&\n\"VOICE_ACTIVATION_MODE_PUSH_TO_TALK\x10\x01\x12#\n\x1fVOICE_ACTIVATION_MODE_WAKE_WORD\x10\x02\x12#\n\x1fVOICE_ACTIVATION_MODE_JUST_TALK\x10\x03\x12\x34\n0VOICE_ACTIVATION_MODE_SILENT_DIALOG_CONTINUATION\x10\x04\x12-\n)VOICE_ACTIVATION_MODE_NAVIGATION_PICKLIST\x10\x05\x12(\n$VOICE_ACTIVATION_MODE_MEDIA_PICKLIST\x10\x06\x12*\n&VOICE_ACTIVATION_MODE_VEHICLE_PICKLIST\x10\x07\x12(\n$VOICE_ACTIVATION_MODE_PHONE_PICKLIST\x10\x08\x12*\n&VOICE_ACTIVATION_MODE_MESSAGE_PICKLIST\x10\t\x12+\n\'VOICE_ACTIVATION_MODE_CALENDAR_PICKLIST\x10\n\x12+\n\'VOICE_ACTIVATION_MODE_REMINDER_PICKLIST\x10\x0b\x12/\n+VOICE_ACTIVATION_MODE_SOCIAL_MEDIA_PICKLIST\x10\x0c\x12*\n&VOICE_ACTIVATION_MODE_GENERIC_PICKLIST\x10\r\x12\"\n\x1eVOICE_ACTIVATION_MODE_VOCATIVE\x10\x0e\x12+\n\'VOICE_ACTIVATION_MODE_CLIENT_SUB_DIALOG\x10\x0f\x12-\n)VOICE_ACTIVATION_MODE_CLOUD_ACTIVE_DIALOG\x10\x10\x42j\n\'com.cerence.cloudservices.api.common.v1B\x18VoiceActivationModeProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.voice_activation_mode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\030VoiceActivationModeProtoP\001Z#cerence/cloudservices/api/common/v1'
  _globals['_VOICEACTIVATIONMODE']._serialized_start=105
  _globals['_VOICEACTIVATIONMODE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
