# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/common/v1/waypoint_blacklist_item.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/common/v1/waypoint_blacklist_item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAcerence/cloudservices/api/common/v1/waypoint_blacklist_item.proto\x12#cerence.cloudservices.api.common.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\xa3\x02\n\x15WaypointBlacklistItem\x12.\n\x08place_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12;\n\x15\x63ontent_provider_name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12*\n\x04name\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nbrand_name\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12?\n\x08\x63\x61tegory\x18\x05 \x01(\x0e\x32-.cerence.cloudservices.api.common.v1.Category*C\n\x08\x43\x61tegory\x12\x18\n\x14\x43\x41TEGORY_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x43\x41TEGORY_CHARGING_STATION\x10\x01\x42l\n\'com.cerence.cloudservices.api.common.v1B\x1aWaypointBlacklistItemProtoP\x01Z#cerence/cloudservices/api/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.common.v1.waypoint_blacklist_item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.cerence.cloudservices.api.common.v1B\032WaypointBlacklistItemProtoP\001Z#cerence/cloudservices/api/common/v1'
  _globals['_CATEGORY']._serialized_start=432
  _globals['_CATEGORY']._serialized_end=499
  _globals['_WAYPOINTBLACKLISTITEM']._serialized_start=139
  _globals['_WAYPOINTBLACKLISTITEM']._serialized_end=430
# @@protoc_insertion_point(module_scope)
