# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/services/user_data/v1/user_data_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/services/user_data/v1/user_data_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEcerence/cloudservices/api/services/user_data/v1/user_data_types.proto\x12/cerence.cloudservices.api.services.user_data.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xc9\x01\n\x0bRequestData\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x18\n\nconcept_id\x18\x03 \x01(\tB\x04\xe2\x41\x01\x02\x12\x62\n\x14product_improvements\x18\x04 \x01(\x0b\x32\x44.cerence.cloudservices.api.services.user_data.v1.ProductImprovements\x12\x18\n\x10response_version\x18\x05 \x01(\t\"\'\n\nUploadDone\x12\x19\n\x0bnew_version\x18\x01 \x01(\x05\x42\x04\xe2\x41\x01\x02\"M\n\x13ProductImprovements\x12\x36\n\x12model_improvements\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\"\x93\x01\n\tDeleteAll\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x62\n\x14product_improvements\x18\x03 \x01(\x0b\x32\x44.cerence.cloudservices.api.services.user_data.v1.ProductImprovementsB|\n3com.cerence.cloudservices.api.services.user_data.v1B\x12UserDataTypesProtoP\x01Z/cerence/cloudservices/api/services/user_data/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.user_data.v1.user_data_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n3com.cerence.cloudservices.api.services.user_data.v1B\022UserDataTypesProtoP\001Z/cerence/cloudservices/api/services/user_data/v1'
  _globals['_REQUESTDATA'].fields_by_name['concept_id']._loaded_options = None
  _globals['_REQUESTDATA'].fields_by_name['concept_id']._serialized_options = b'\342A\001\002'
  _globals['_UPLOADDONE'].fields_by_name['new_version']._loaded_options = None
  _globals['_UPLOADDONE'].fields_by_name['new_version']._serialized_options = b'\342A\001\002'
  _globals['_REQUESTDATA']._serialized_start=188
  _globals['_REQUESTDATA']._serialized_end=389
  _globals['_UPLOADDONE']._serialized_start=391
  _globals['_UPLOADDONE']._serialized_end=430
  _globals['_PRODUCTIMPROVEMENTS']._serialized_start=432
  _globals['_PRODUCTIMPROVEMENTS']._serialized_end=509
  _globals['_DELETEALL']._serialized_start=512
  _globals['_DELETEALL']._serialized_end=659
# @@protoc_insertion_point(module_scope)
