// Copyright © 2022-2025 Cerence Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the “Software”),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

syntax = "proto3";

package cerence.cloudservices.api.services.nlu.v1;

import "cerence/cloudservices/api/common/v1/audio_format.proto";
import "cerence/cloudservices/api/common/v1/concept.proto";
import "cerence/cloudservices/api/common/v1/feature_inventory.proto";
import "cerence/cloudservices/api/common/v1/interaction_history.proto";
import "cerence/cloudservices/api/common/v1/interpretation.proto";
import "cerence/cloudservices/api/common/v1/nlu_result_for_arbitration.proto";
import "cerence/cloudservices/api/common/v1/personal_assistant_request.proto";
import "cerence/cloudservices/api/common/v1/profanity_filter.proto";
import "cerence/cloudservices/api/common/v1/query_status.proto";
import "cerence/cloudservices/api/common/v1/voice_activation_mode.proto";
import "cerence/cloudservices/api/common/v1/response_config.proto";
import "cerence/cloudservices/api/dialog/v1/pnp_dialog_streaming_response_continuation.proto";
import "cerence/cloudservices/api/dialog/v1/dialog_context.proto";
import "cerence/cloudservices/api/services/asr/v1/asr_result.proto";
import "cerence/cloudservices/api/services/nlu/v1/nlu_context.proto";
import "cerence/cloudservices/api/services/nlu/v1/diagnostic.proto";
import "cerence/cloudservices/api/services/user_data/v1/input_data.proto";
import "cerence/cloudservices/domain/common/dialog/v1/dialog_interaction.proto";

import "google/rpc/status.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/any.proto";
import "google/protobuf/wrappers.proto";

option go_package = "cerence/cloudservices/api/services/nlu/v1";
option java_multiple_files = true;
option java_outer_classname = "NluApiProto";
option java_package = "com.cerence.cloudservices.api.services.nlu.v1";

// Service that implements the Cerence API for NLU requests
service NluQueryService {

  // Performs an NLU query request.
  rpc StreamingNluQuery (stream StreamingNluQueryRequest) returns (stream StreamingNluQueryResponse);
}

// The top-level message sent by the client for the 'StreamingNluQuery' method.
// Multiple 'StreamingNluQueryRequest' messages are sent.  The first message must contain a 'request_data'
// message and must not contain 'audio'.  All subsequent messages must contain 'audio' and must not contain an
// 'request_data' message.
message StreamingNluQueryRequest {
  oneof streaming_request {
    // Provides information to the cloud services api that is required to complete the NLU query.
    // The first 'StreamingNluQueryRequest' message must contain a 'request_data' message.
    RequestData request_data = 1;

    // The audio data to be recognized.  Sequential chunks of audio data are sent in sequential
    // 'StreamingNluQueryRequest' messages.  The first 'StreamingNluQueryRequest' message must not
    // contain 'audio' data and all subsequent 'StreamingNluQueryRequest' messages must contain 'audio' data.
    // The audio bytes must be encoded as specified in the 'RequestData' message 'audio_format' field.
    // Note: as with all bytes fields, proto buffers use a pure binary representation (not base64).
    bytes audio = 2;

    // Aborts session with reason. Different reasons can result in different abort behaviours and side effects cloud side.
    Abort abort = 3;
  }
}

// Request aborting session and provide reason.
message Abort {
  AbortReason reason = 1 [(google.api.field_behavior) = REQUIRED];
}

enum AbortReason {
  // Session ended for unspecified reasons
  ABORT_REASON_UNSPECIFIED = 0;

  // Wake up detected on client side. The audio received so far was not intended for the cloud nlu.
  ABORT_REASON_WUW_DETECTED = 1;

  // Session was ended because the user aborted it
  ABORT_REASON_USER_ABORT = 2;

  // Session was ended because of an error
  ABORT_REASON_ERROR = 3;

  // Session was ended as request timed out
  ABORT_REASON_TIMEOUT = 4;

  // Session ended for unknown reasons
  ABORT_REASON_UNKNOWN = 5;
}

// The message returned to the client by 'StreamingNluQueryRequest'
// A series of one or more 'StreamingNluQueryResponse' messages are streamed back to the client
message StreamingNluQueryResponse {
  NluResponse response = 1;
}

// Provides information on how to process the request.
message RequestData {
  // A string that uniquely identifies the user making the request. The value must not be empty and must have a maximum size of 64 characters.
  string user_id = 1;

  // Format of the audio that will be sent from client.
  cerence.cloudservices.api.common.v1.AudioFormat audio_format = 2 [(google.api.field_behavior) = REQUIRED];

  // Configures profanity filtering in the response
  cerence.cloudservices.api.common.v1.ProfanityFilter profanity_filter = 3;

  // Provides context information
  Context  context = 4;

  // User interaction history
  repeated cerence.cloudservices.api.common.v1.InteractionHistory interaction_history = 5;

  // The serialized session state from the previous response.
  // The session data is common across all services
  bytes session_data = 6;

  // Response Version
  string response_version = 7;

  // Dialog data
  Dialog dialog = 8;

  // The logging information that can be passed in the request.
  Logging logging = 9;

  // Personal assistant request data
  cerence.cloudservices.api.common.v1.PersonalAssistantRequest personal_assistant_request = 10;

  // Product Improvements
  ProductImprovements product_improvements = 11;

  // The device id allows to differentiate between devices. The value must not be empty and must have a maximum size of 64 characters.
  string device_id = 12;

  // A list of user data resources to use with the request.
  repeated UserDataResource user_data_resources = 13;

  // The activation mode for voice requests.
  cerence.cloudservices.api.common.v1.VoiceActivationMode voice_activation_mode = 14;

  // Optional user speech offset. If provided, number of milliseconds to skip before starting ASR recognition
  // The audio before that timestamp may be used to improve the recognition (e.g. acoustic adaptation)
  int32 user_speech_offset_ms = 15;

  // A list of transient data (custom word resources) to use with the request.
  // Provides "hints" in order to favor specific words and phrases in the results
  repeated InlineGrammarResource inline_grammar_resources = 16;

  // Cloud response configuration
  cerence.cloudservices.api.common.v1.ResponseConfig response_config = 17;
}

message Dialog {
  // Object that contains session scoped variables and transaction scoped variables that can
  // be exchanged between client and cloud dialog engine
  cerence.cloudservices.api.dialog.v1.DialogContext context = 1;

  // Used to provide information about client dialog state that may influence the cloud behavior.
  cerence.cloudservices.api.dialog.v1.ClientDialogContext client_dialog_context = 2;
}

message Logging {
  // Client dialog id. Provide the same value for all requests made within a dialog. Must be a globally unique id.
  string client_dialog_id = 1;

  // Identifies an interaction within a dialog. Must be a valid uuid.
  string client_interaction_uuid = 2;
}

message UserDataResource {
  // The version of the previously uploaded user data resource.
  int32 expected_version = 1;

  // The concept identifying the uploaded user data resource.
  cerence.cloudservices.api.common.v1.Concept concept = 2;
}

message InlineGrammarResource {
  // (Optional) The concept identifying the inline grammar resource, mainly used for debugging purpose. If present, the type of this concept should match the message in transient_data.
  cerence.cloudservices.api.common.v1.Concept concept = 1;

  // Transient data to use with the request.
  oneof transient_data {
    cerence.cloudservices.api.services.user_data.v1.CustomWords custom_words = 2;
  }
}

message ProductImprovements {
  // A flag to allow the driver to opt-out from using his or her data for further data model improvements.
  // Default value if not specified is 'true'.
  google.protobuf.BoolValue model_improvements = 1;
}

// The message returned to the client when the recognition and natural language understanding results are streamed
message NluResponse {
  // If set, returns a [google.rpc.Status][google.rpc.Status] message that
  // specifies the status of the current response.
  // It returns the status per response while the streaming of results continues.
  // This is especially useful for word streaming or utterance detection use cases where it facilitates
  // returning the status per response while the streaming of results continues.

  // google.rpc.Status messages that can be returned:
  // | Code | Message              | Description
  // ----------------------------------------------------------------------------------------
  // | 3    | Invalid Argument     | Invalid request from client.
  // | 7    | PermissionDenied     | Request with invalid subscription.
  // | 9    | Failed Precondition  | No geo-coordinates provided.
  // | 10   | Aborted              | No ASR recognition match (ASR and NLU requests only).
  // | 13   | Internal             | Error from server or downstream services.
  google.rpc.Status status = 1;

  // The response will contain the ASR result or the NLU result
  oneof streaming_result {
    cerence.cloudservices.api.common.v1.QueryStarted query_started = 7;

    // Intermediate result for the speech recognition.
    // The first 'NluResponse' message must contain an 'intermediate_asr_result' message when utterance
    // detection is off.
    // Multiple 'intermediate_asr_result' messages may be sent.
    IntermediateAsrResult intermediate_asr_result = 2;

    FinalAsrResult final_asr_result = 3;

    cerence.cloudservices.api.common.v1.NluResultForArbitration nlu_result_for_arbitration = 6;

    DomainResult domain_result = 4;

    // Deprecated, replaced by 'domain_result_continuation' field.
    cerence.cloudservices.api.dialog.v1.PlugAndPlayDialogStreamingResponseContinuation pnp_dialog_information = 8 [deprecated = true];

    // If domain streaming response feature is enabled, then after domain result and before the metadata, 
    // the cloud will stream back this dialog result continuation, which includes the facet chunks or other info in chunks.
    DomainResultContinuation domain_result_continuation = 9;

    // The metadata information will always be returned last (even for error scenarios).
    Metadata metadata = 5;
  }
}

message IntermediateAsrResult {
  cerence.cloudservices.api.services.asr.v1.AsrResult asr_result = 1;
}

message FinalAsrResult {
  // This contains the final ASR result including semantically annotated tokens
  cerence.cloudservices.api.services.asr.v1.AsrResult asr_result = 1;
}

message DomainResult {
  // One of the domain results defined in /proto/cerence/cloudservices/domain/results/*.proto
  google.protobuf.Any result = 1;

  cerence.cloudservices.api.common.v1.Interpretations interpretations = 2;

  repeated cerence.cloudservices.api.common.v1.InteractionHistory interaction_history = 3;

  bytes session_data = 4;

  ExtraInfo extra_info = 5;

  repeated cerence.cloudservices.api.common.v1.FeatureInventory features_inventory = 6;
}

message DomainResultContinuation {
  // One of the domain streaming result continuations defined in /proto/cerence/cloudservices/domain/results/*.proto,
  // where the message has a suffix of 'StreamingResponseContinuation'.
  google.protobuf.Any continuation = 1;

  // Optional, the up-to-date latest interaction history slot
  // If it's present, then client shall use it to overwrite the latest interaction history slot in the dialog result.
  cerence.cloudservices.api.common.v1.InteractionHistory interaction_history = 2;

  // Optional, the latest session data 
  // If it's present, then client shall use it as the up-to-date session data.
  bytes session_data = 3;
}

message ExtraInfo {
  // If the user's utterance has been rewritten, then there will be an explanation text.
  cerence.cloudservices.domain.common.dialog.v1.Interaction rewritten_explanation = 1;
}

// The metadata information
message Metadata {
  repeated cerence.cloudservices.api.services.asr.v1.RecognitionResourceMetaInformation resource_meta_infos = 1;

  VersionInformation version_info = 2;

  DiagnosticInformation diagnostic_info = 3;

  AudioStatistics audio_stat = 4;
}
