# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/common/v1/content_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/common/v1/content_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJcerence/cloudservices/domain/common/content/common/v1/content_status.proto\x12\x35\x63\x65rence.cloudservices.domain.common.content.common.v1\"\xc1\x02\n\x11\x43ontentStatusInfo\x12\\\n\x0e\x63ontent_status\x18\x01 \x01(\x0e\x32\x44.cerence.cloudservices.domain.common.content.common.v1.ContentStatus\x12k\n\x16\x63ontent_failure_reason\x18\x02 \x01(\x0e\x32K.cerence.cloudservices.domain.common.content.common.v1.ContentFailureReason\x12\x61\n\x11no_content_reason\x18\x03 \x01(\x0e\x32\x46.cerence.cloudservices.domain.common.content.common.v1.NoContentReason*\x86\x01\n\rContentStatus\x12\x1e\n\x1a\x43ONTENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x43ONTENT_STATUS_NO_CONTENT\x10\x01\x12\x1a\n\x16\x43ONTENT_STATUS_FAILURE\x10\x02\x12\x1a\n\x16\x43ONTENT_STATUS_CONTENT\x10\x03*\xa6\x01\n\x14\x43ontentFailureReason\x12&\n\"CONTENT_FAILURE_REASON_UNSPECIFIED\x10\x00\x12(\n$CONTENT_FAILURE_REASON_GENERIC_ERROR\x10\x01\x12<\n8CONTENT_FAILURE_REASON_FAILURE_TO_RETRIEVE_FROM_PROVIDER\x10\x02*\x96\x02\n\x0fNoContentReason\x12!\n\x1dNO_CONTENT_REASON_UNSPECIFIED\x10\x00\x12 \n\x1cNO_CONTENT_REASON_NO_RESULTS\x10\x01\x12\'\n#NO_CONTENT_REASON_QUERY_UNSUPPORTED\x10\x02\x12)\n%NO_CONTENT_REASON_UNRESOLVED_ANAPHORA\x10\x03\x12@\n<NO_CONTENT_REASON_MISSING_LOCATION_REFERENCE_INPUT_PARAMETER\x10\x04\x12(\n$NO_CONTENT_REASON_LOCATION_NOT_FOUND\x10\x05\x42\x88\x01\n9com.cerence.cloudservices.domain.common.content.common.v1B\x12\x43ontentStatusProtoP\x01Z5cerence/cloudservices/domain/common/content/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.common.v1.content_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n9com.cerence.cloudservices.domain.common.content.common.v1B\022ContentStatusProtoP\001Z5cerence/cloudservices/domain/common/content/common/v1'
  _globals['_CONTENTSTATUS']._serialized_start=458
  _globals['_CONTENTSTATUS']._serialized_end=592
  _globals['_CONTENTFAILUREREASON']._serialized_start=595
  _globals['_CONTENTFAILUREREASON']._serialized_end=761
  _globals['_NOCONTENTREASON']._serialized_start=764
  _globals['_NOCONTENTREASON']._serialized_end=1042
  _globals['_CONTENTSTATUSINFO']._serialized_start=134
  _globals['_CONTENTSTATUSINFO']._serialized_end=455
# @@protoc_insertion_point(module_scope)
