# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cerence.cloudservices.api.services.nlu.v1 import nlu_api_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_nlu_dot_v1_dot_nlu__api__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cerence/cloudservices/api/services/nlu/v1/nlu_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NluQueryServiceStub(object):
    """Service that implements the Cerence API for NLU requests
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamingNluQuery = channel.stream_stream(
                '/cerence.cloudservices.api.services.nlu.v1.NluQueryService/StreamingNluQuery',
                request_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_nlu_dot_v1_dot_nlu__api__pb2.StreamingNluQueryRequest.SerializeToString,
                response_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_nlu_dot_v1_dot_nlu__api__pb2.StreamingNluQueryResponse.FromString,
                _registered_method=True)


class NluQueryServiceServicer(object):
    """Service that implements the Cerence API for NLU requests
    """

    def StreamingNluQuery(self, request_iterator, context):
        """Performs an NLU query request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NluQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamingNluQuery': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingNluQuery,
                    request_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_nlu_dot_v1_dot_nlu__api__pb2.StreamingNluQueryRequest.FromString,
                    response_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_nlu_dot_v1_dot_nlu__api__pb2.StreamingNluQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cerence.cloudservices.api.services.nlu.v1.NluQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cerence.cloudservices.api.services.nlu.v1.NluQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NluQueryService(object):
    """Service that implements the Cerence API for NLU requests
    """

    @staticmethod
    def StreamingNluQuery(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cerence.cloudservices.api.services.nlu.v1.NluQueryService/StreamingNluQuery',
            cerence_dot_cloudservices_dot_api_dot_services_dot_nlu_dot_v1_dot_nlu__api__pb2.StreamingNluQueryRequest.SerializeToString,
            cerence_dot_cloudservices_dot_api_dot_services_dot_nlu_dot_v1_dot_nlu__api__pb2.StreamingNluQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
