# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/media/v1/artist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.media.v1 import visual_content_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_visual__content__pb2
from cerence.cloudservices.domain.common.content.media.v1 import genres_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_genres__pb2
from cerence.cloudservices.domain.common.content.media.v1 import spotify_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_spotify__pb2
from cerence.cloudservices.domain.common.content.media.v1 import amazon_music_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_amazon__music__pb2
from cerence.cloudservices.domain.common.content.media.v1 import apple_music_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_apple__music__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAcerence/cloudservices/domain/common/content/media/v1/artist.proto\x12\x34\x63\x65rence.cloudservices.domain.common.content.media.v1\x1aIcerence/cloudservices/domain/common/content/media/v1/visual_content.proto\x1a\x41\x63\x65rence/cloudservices/domain/common/content/media/v1/genres.proto\x1a\x42\x63\x65rence/cloudservices/domain/common/content/media/v1/spotify.proto\x1aGcerence/cloudservices/domain/common/content/media/v1/amazon_music.proto\x1a\x46\x63\x65rence/cloudservices/domain/common/content/media/v1/apple_music.proto\"\xc7\x04\n\x06\x41rtist\x12W\n\tbase_info\x18\x01 \x01(\x0b\x32\x44.cerence.cloudservices.domain.common.content.media.v1.ArtistBaseInfo\x12K\n\x06genres\x18\x02 \x03(\x0b\x32;.cerence.cloudservices.domain.common.content.media.v1.Genre\x12R\n\x05media\x18\x03 \x03(\x0b\x32\x43.cerence.cloudservices.domain.common.content.media.v1.VisualContent\x12\x61\n\x10spotify_metadata\x18\x04 \x01(\x0b\x32\x45.cerence.cloudservices.domain.common.content.media.v1.SpotifyMetadataH\x00\x12j\n\x15\x61mazon_music_metadata\x18\x05 \x01(\x0b\x32I.cerence.cloudservices.domain.common.content.media.v1.AmazonMusicMetadataH\x00\x12h\n\x14\x61pple_music_metadata\x18\x06 \x01(\x0b\x32H.cerence.cloudservices.domain.common.content.media.v1.AppleMusicMetadataH\x00\x42\n\n\x08metadata\"*\n\x0e\x41rtistBaseInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tB\x7f\n8com.cerence.cloudservices.domain.common.content.media.v1B\x0b\x41rtistProtoP\x01Z4cerence/cloudservices/domain/common/content/media/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.media.v1.artist_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n8com.cerence.cloudservices.domain.common.content.media.v1B\013ArtistProtoP\001Z4cerence/cloudservices/domain/common/content/media/v1'
  _ARTIST._serialized_start=479
  _ARTIST._serialized_end=1062
  _ARTISTBASEINFO._serialized_start=1064
  _ARTISTBASEINFO._serialized_end=1106
# @@protoc_insertion_point(module_scope)
