# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/media/v1/content_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.media.v1 import media_content_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_media__content__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIcerence/cloudservices/domain/common/content/media/v1/content_status.proto\x12\x34\x63\x65rence.cloudservices.domain.common.content.media.v1\x1aHcerence/cloudservices/domain/common/content/media/v1/media_content.proto\"\xdc\x01\n\x12MediaContentStatus\x12P\n\x08provider\x18\x01 \x01(\x0b\x32>.cerence.cloudservices.domain.common.content.media.v1.Provider\x12\\\n\x0e\x63ontent_status\x18\x02 \x01(\x0e\x32\x44.cerence.cloudservices.domain.common.content.media.v1.ProviderStatus\x12\x16\n\x0e\x63ontent_reason\x18\x03 \x01(\t*\x86\x02\n\x0eProviderStatus\x12\x1f\n\x1bPROVIDER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12PROVIDER_STATUS_OK\x10\x01\x12\x1e\n\x1aPROVIDER_STATUS_NO_CONTENT\x10\x02\x12!\n\x1dPROVIDER_STATUS_TOKEN_INVALID\x10\x03\x12!\n\x1dPROVIDER_STATUS_MISSING_TOKEN\x10\x04\x12+\n\'PROVIDER_STATUS_PROVIDER_INTERNAL_ERROR\x10\x05\x12(\n$PROVIDER_STATUS_MEDIA_INTERNAL_ERROR\x10\x06\x42\x8b\x01\n8com.cerence.cloudservices.domain.common.content.media.v1B\x17MediaContentStatusProtoP\x01Z4cerence/cloudservices/domain/common/content/media/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.media.v1.content_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n8com.cerence.cloudservices.domain.common.content.media.v1B\027MediaContentStatusProtoP\001Z4cerence/cloudservices/domain/common/content/media/v1'
  _PROVIDERSTATUS._serialized_start=429
  _PROVIDERSTATUS._serialized_end=691
  _MEDIACONTENTSTATUS._serialized_start=206
  _MEDIACONTENTSTATUS._serialized_end=426
# @@protoc_insertion_point(module_scope)
