# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/media/v1/http_based_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNcerence/cloudservices/domain/common/content/media/v1/http_based_metadata.proto\x12\x34\x63\x65rence.cloudservices.domain.common.content.media.v1\"n\n\x10HttpSongMetadata\x12Z\n\x0bweb_content\x18\x01 \x03(\x0b\x32\x45.cerence.cloudservices.domain.common.content.media.v1.HttpSongContent\"\xbe\x01\n\x0fHttpSongContent\x12\x0b\n\x03url\x18\x01 \x01(\t\x12P\n\x06\x66ormat\x18\x02 \x01(\x0e\x32@.cerence.cloudservices.domain.common.content.media.v1.SongFormat\x12L\n\x04type\x18\x03 \x01(\x0e\x32>.cerence.cloudservices.domain.common.content.media.v1.SongType*>\n\nSongFormat\x12\x1b\n\x17SONG_FORMAT_UNSPECIFIED\x10\x00\x12\x13\n\x0fSONG_FORMAT_MP4\x10\x01*e\n\x08SongType\x12\x19\n\x15SONG_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17SONG_TYPE_ORIGINAL_SONG\x10\x01\x12!\n\x1dSONG_TYPE_WITHOUT_LEAD_VOCALS\x10\x02\x42\x85\x01\n8com.cerence.cloudservices.domain.common.content.media.v1B\x11HttpMetadataProtoP\x01Z4cerence/cloudservices/domain/common/content/media/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.media.v1.http_based_metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n8com.cerence.cloudservices.domain.common.content.media.v1B\021HttpMetadataProtoP\001Z4cerence/cloudservices/domain/common/content/media/v1'
  _SONGFORMAT._serialized_start=441
  _SONGFORMAT._serialized_end=503
  _SONGTYPE._serialized_start=505
  _SONGTYPE._serialized_end=606
  _HTTPSONGMETADATA._serialized_start=136
  _HTTPSONGMETADATA._serialized_end=246
  _HTTPSONGCONTENT._serialized_start=249
  _HTTPSONGCONTENT._serialized_end=439
# @@protoc_insertion_point(module_scope)
