# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/media/v1/sirius_xm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcerence/cloudservices/domain/common/content/media/v1/sirius_xm.proto\x12\x34\x63\x65rence.cloudservices.domain.common.content.media.v1\"\x9a\x01\n\x17SiriusXMChannelMetadata\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x19\n\x11short_description\x18\x02 \x01(\t\x12\x18\n\x10long_description\x18\x03 \x01(\t\x12\x0f\n\x07line_up\x18\x04 \x03(\x05\x12\x16\n\x0estreaming_name\x18\x05 \x01(\t\x12\x13\n\x0btune_method\x18\x06 \x01(\t\"\xc8\x01\n\x14SiriusXMShowMetadata\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x13\n\x0bshort_title\x18\x02 \x01(\t\x12\x12\n\nlong_title\x18\x03 \x01(\t\x12\x18\n\x10long_description\x18\x04 \x01(\t\x12_\n\x08\x63hannels\x18\x05 \x03(\x0b\x32M.cerence.cloudservices.domain.common.content.media.v1.SiriusXMChannelMetadataB\x81\x01\n8com.cerence.cloudservices.domain.common.content.media.v1B\rSiriusXMProtoP\x01Z4cerence/cloudservices/domain/common/content/media/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.media.v1.sirius_xm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n8com.cerence.cloudservices.domain.common.content.media.v1B\rSiriusXMProtoP\001Z4cerence/cloudservices/domain/common/content/media/v1'
  _SIRIUSXMCHANNELMETADATA._serialized_start=127
  _SIRIUSXMCHANNELMETADATA._serialized_end=281
  _SIRIUSXMSHOWMETADATA._serialized_start=284
  _SIRIUSXMSHOWMETADATA._serialized_end=484
# @@protoc_insertion_point(module_scope)
