# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/media/v1/spotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBcerence/cloudservices/domain/common/content/media/v1/spotify.proto\x12\x34\x63\x65rence.cloudservices.domain.common.content.media.v1\"\x1e\n\x0fSpotifyMetadata\x12\x0b\n\x03url\x18\x01 \x01(\tB\x80\x01\n8com.cerence.cloudservices.domain.common.content.media.v1B\x0cSpotifyProtoP\x01Z4cerence/cloudservices/domain/common/content/media/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.media.v1.spotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n8com.cerence.cloudservices.domain.common.content.media.v1B\014SpotifyProtoP\001Z4cerence/cloudservices/domain/common/content/media/v1'
  _SPOTIFYMETADATA._serialized_start=124
  _SPOTIFYMETADATA._serialized_end=154
# @@protoc_insertion_point(module_scope)
