# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/ude/v1/local_search_detail.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.common.v1 import common_detail_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_common_dot_v1_dot_common__detail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLcerence/cloudservices/domain/common/content/ude/v1/local_search_detail.proto\x12\x32\x63\x65rence.cloudservices.domain.common.content.ude.v1\x1aIcerence/cloudservices/domain/common/content/common/v1/common_detail.proto\"\xf1\x02\n\x11LocalSearchDetail\x12\x15\n\raccessibility\x18\x01 \x01(\x08\x12^\n\x0foperating_hours\x18\x02 \x01(\x0b\x32\x45.cerence.cloudservices.domain.common.content.common.v1.OperatingHours\x12\r\n\x05price\x18\x03 \x01(\t\x12J\n\x06rating\x18\x04 \x01(\x0b\x32:.cerence.cloudservices.domain.common.content.ude.v1.Rating\x12\x11\n\trestrooms\x18\x05 \x01(\x08\x12\x0c\n\x04wifi\x18\x06 \x01(\t\x12\x0f\n\x07yelp_id\x18\x07 \x01(\t\x12X\n\x0fyelp_categories\x18\x08 \x03(\x0b\x32?.cerence.cloudservices.domain.common.content.common.v1.Category\"\x81\x01\n\x06Rating\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\x0f\n\x07\x61verage\x18\x02 \x01(\x01\x12W\n\x0b\x61ttribution\x18\x03 \x01(\x0b\x32\x42.cerence.cloudservices.domain.common.content.common.v1.AttributionB\x86\x01\n6com.cerence.cloudservices.domain.common.content.ude.v1B\x16LocalSearchDetailProtoP\x01Z2cerence/cloudservices/domain/common/content/ude/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.ude.v1.local_search_detail_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n6com.cerence.cloudservices.domain.common.content.ude.v1B\026LocalSearchDetailProtoP\001Z2cerence/cloudservices/domain/common/content/ude/v1'
  _LOCALSEARCHDETAIL._serialized_start=208
  _LOCALSEARCHDETAIL._serialized_end=577
  _RATING._serialized_start=580
  _RATING._serialized_end=709
# @@protoc_insertion_point(module_scope)
