# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/ude/v1/reservation_detail.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.common.v1 import common_detail_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_common_dot_v1_dot_common__detail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKcerence/cloudservices/domain/common/content/ude/v1/reservation_detail.proto\x12\x32\x63\x65rence.cloudservices.domain.common.content.ude.v1\x1aIcerence/cloudservices/domain/common/content/common/v1/common_detail.proto\"d\n\x11ReservationDetail\x12O\n\tproviders\x18\x01 \x03(\x0b\x32<.cerence.cloudservices.domain.common.content.ude.v1.Provider\"\xc6\x01\n\x08Provider\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x11\n\tphoto_url\x18\x03 \x01(\t\x12\x1b\n\x13restaurant_page_url\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\t\x12M\n\x06rating\x18\x06 \x01(\x0b\x32=.cerence.cloudservices.domain.common.content.common.v1.Rating\x12\x12\n\npopularity\x18\x07 \x01(\tB\x86\x01\n6com.cerence.cloudservices.domain.common.content.ude.v1B\x16ReservationDetailProtoP\x01Z2cerence/cloudservices/domain/common/content/ude/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.ude.v1.reservation_detail_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n6com.cerence.cloudservices.domain.common.content.ude.v1B\026ReservationDetailProtoP\001Z2cerence/cloudservices/domain/common/content/ude/v1'
  _RESERVATIONDETAIL._serialized_start=206
  _RESERVATIONDETAIL._serialized_end=306
  _PROVIDER._serialized_start=309
  _PROVIDER._serialized_end=507
# @@protoc_insertion_point(module_scope)
