# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cerence.cloudservices.api.services.device_heartbeat.v1 import device_heartbeat_api_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_device__heartbeat_dot_v1_dot_device__heartbeat__api__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cerence/cloudservices/api/services/device_heartbeat/v1/device_heartbeat_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceHeartbeatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeviceHeartbeat = channel.unary_stream(
                '/cerence.cloudservices.api.services.device_heartbeat.v1.DeviceHeartbeatService/DeviceHeartbeat',
                request_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_device__heartbeat_dot_v1_dot_device__heartbeat__api__pb2.DeviceHeartbeatRequest.SerializeToString,
                response_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_device__heartbeat_dot_v1_dot_device__heartbeat__api__pb2.StreamingDeviceHeartbeatResponse.FromString,
                _registered_method=True)


class DeviceHeartbeatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeviceHeartbeat(self, request, context):
        """Performs a device heartbeat request from client side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceHeartbeatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeviceHeartbeat': grpc.unary_stream_rpc_method_handler(
                    servicer.DeviceHeartbeat,
                    request_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_device__heartbeat_dot_v1_dot_device__heartbeat__api__pb2.DeviceHeartbeatRequest.FromString,
                    response_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_device__heartbeat_dot_v1_dot_device__heartbeat__api__pb2.StreamingDeviceHeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cerence.cloudservices.api.services.device_heartbeat.v1.DeviceHeartbeatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cerence.cloudservices.api.services.device_heartbeat.v1.DeviceHeartbeatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceHeartbeatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeviceHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cerence.cloudservices.api.services.device_heartbeat.v1.DeviceHeartbeatService/DeviceHeartbeat',
            cerence_dot_cloudservices_dot_api_dot_services_dot_device__heartbeat_dot_v1_dot_device__heartbeat__api__pb2.DeviceHeartbeatRequest.SerializeToString,
            cerence_dot_cloudservices_dot_api_dot_services_dot_device__heartbeat_dot_v1_dot_device__heartbeat__api__pb2.StreamingDeviceHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
