# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/services/device_heartbeat/v1/device_heartbeat_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/services/device_heartbeat/v1/device_heartbeat_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.api.services.device_heartbeat.v1 import diagnostic_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_device__heartbeat_dot_v1_dot_diagnostic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQcerence/cloudservices/api/services/device_heartbeat/v1/device_heartbeat_api.proto\x12\x36\x63\x65rence.cloudservices.api.services.device_heartbeat.v1\x1aGcerence/cloudservices/api/services/device_heartbeat/v1/diagnostic.proto\"Q\n\x16\x44\x65viceHeartbeatRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0bsdk_version\x18\x03 \x01(\t\"\x8c\x01\n StreamingDeviceHeartbeatResponse\x12T\n\x08metadata\x18\x01 \x01(\x0b\x32@.cerence.cloudservices.api.services.device_heartbeat.v1.MetadataH\x00\x42\x12\n\x10streaming_result\"\xd4\x01\n\x08Metadata\x12`\n\x0cversion_info\x18\x01 \x01(\x0b\x32J.cerence.cloudservices.api.services.device_heartbeat.v1.VersionInformation\x12\x66\n\x0f\x64iagnostic_info\x18\x02 \x01(\x0b\x32M.cerence.cloudservices.api.services.device_heartbeat.v1.DiagnosticInformation2\xd8\x01\n\x16\x44\x65viceHeartbeatService\x12\xbd\x01\n\x0f\x44\x65viceHeartbeat\x12N.cerence.cloudservices.api.services.device_heartbeat.v1.DeviceHeartbeatRequest\x1aX.cerence.cloudservices.api.services.device_heartbeat.v1.StreamingDeviceHeartbeatResponse0\x01\x42\x8f\x01\n:com.cerence.cloudservices.api.services.device_heartbeat.v1B\x17\x44\x65viceHeartbeatApiProtoP\x00Z6cerence/cloudservices/api/services/device_heartbeat/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.device_heartbeat.v1.device_heartbeat_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n:com.cerence.cloudservices.api.services.device_heartbeat.v1B\027DeviceHeartbeatApiProtoP\000Z6cerence/cloudservices/api/services/device_heartbeat/v1'
  _globals['_DEVICEHEARTBEATREQUEST']._serialized_start=214
  _globals['_DEVICEHEARTBEATREQUEST']._serialized_end=295
  _globals['_STREAMINGDEVICEHEARTBEATRESPONSE']._serialized_start=298
  _globals['_STREAMINGDEVICEHEARTBEATRESPONSE']._serialized_end=438
  _globals['_METADATA']._serialized_start=441
  _globals['_METADATA']._serialized_end=653
  _globals['_DEVICEHEARTBEATSERVICE']._serialized_start=656
  _globals['_DEVICEHEARTBEATSERVICE']._serialized_end=872
# @@protoc_insertion_point(module_scope)
