# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/sing/v1/sing_media.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.sing.v1 import sing_prompt_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_sing_dot_v1_dot_sing__prompt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcerence/cloudservices/domain/common/content/sing/v1/sing_media.proto\x12\x33\x63\x65rence.cloudservices.domain.common.content.sing.v1\x1a\x45\x63\x65rence/cloudservices/domain/common/content/sing/v1/sing_prompt.proto\"\x9e\x02\n\tSingMedia\x12\x0c\n\x04seek\x18\x01 \x01(\x02\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02\x12]\n\x12\x64ialog_interaction\x18\x03 \x01(\x0b\x32\x41.cerence.cloudservices.domain.common.content.sing.v1.DialogPrompt\x12X\n\rmedia_content\x18\x04 \x03(\x0b\x32\x41.cerence.cloudservices.domain.common.content.sing.v1.MediaContent\x12\x11\n\tsong_name\x18\x05 \x01(\t\x12\x13\n\x0b\x61rtist_name\x18\x06 \x03(\t\x12\x10\n\x08media_id\x18\x07 \x01(\t\"\xc6\x01\n\x0cMediaContent\x12R\n\nmedia_type\x18\x01 \x01(\x0e\x32>.cerence.cloudservices.domain.common.content.sing.v1.MediaType\x12X\n\x0chttp_content\x18\x02 \x01(\x0b\x32@.cerence.cloudservices.domain.common.content.sing.v1.HttpContentH\x00\x42\x08\n\x06source\"p\n\x0bHttpContent\x12T\n\x0bsong_format\x18\x01 \x01(\x0e\x32?.cerence.cloudservices.domain.common.content.sing.v1.SongFormat\x12\x0b\n\x03url\x18\x02 \x01(\t*>\n\nSongFormat\x12\x1b\n\x17SONG_FORMAT_UNSPECIFIED\x10\x00\x12\x13\n\x0fSONG_FORMAT_MP4\x10\x01*d\n\tMediaType\x12\x1a\n\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13MEDIA_TYPE_ORIGINAL\x10\x01\x12\"\n\x1eMEDIA_TYPE_WITHOUT_LEAD_VOCALS\x10\x02\x42\x80\x01\n7com.cerence.cloudservices.domain.common.content.sing.v1B\x0eSingMediaProtoP\x01Z3cerence/cloudservices/domain/common/content/sing/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.sing.v1.sing_media_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n7com.cerence.cloudservices.domain.common.content.sing.v1B\016SingMediaProtoP\001Z3cerence/cloudservices/domain/common/content/sing/v1'
  _SONGFORMAT._serialized_start=800
  _SONGFORMAT._serialized_end=862
  _MEDIATYPE._serialized_start=864
  _MEDIATYPE._serialized_end=964
  _SINGMEDIA._serialized_start=197
  _SINGMEDIA._serialized_end=483
  _MEDIACONTENT._serialized_start=486
  _MEDIACONTENT._serialized_end=684
  _HTTPCONTENT._serialized_start=686
  _HTTPCONTENT._serialized_end=798
# @@protoc_insertion_point(module_scope)
