# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/sing/v1/sing_prompt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEcerence/cloudservices/domain/common/content/sing/v1/sing_prompt.proto\x12\x33\x63\x65rence.cloudservices.domain.common.content.sing.v1\"D\n\x0c\x44ialogPrompt\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x03tts\x18\x02 \x01(\tH\x00\x12\x0e\n\x04ssml\x18\x03 \x01(\tH\x00\x42\x07\n\x05inputB\x81\x01\n7com.cerence.cloudservices.domain.common.content.sing.v1B\x0fSingDialogProtoP\x01Z3cerence/cloudservices/domain/common/content/sing/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.sing.v1.sing_prompt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n7com.cerence.cloudservices.domain.common.content.sing.v1B\017SingDialogProtoP\001Z3cerence/cloudservices/domain/common/content/sing/v1'
  _DIALOGPROMPT._serialized_start=126
  _DIALOGPROMPT._serialized_end=194
# @@protoc_insertion_point(module_scope)
