// Copyright © 2022 Cerence Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the “Software”),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

syntax = "proto3";

package cerence.cloudservices.domain.common.content.ude.v1;

import "cerence/cloudservices/domain/common/content/common/v1/common_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/ai_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/core_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/ev_charging_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/fuel_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/local_search_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/multimodal_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/parking_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/reservation_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/wiki_detail.proto";
import "cerence/cloudservices/domain/common/content/ude/v1/promotion.proto";

import "google/protobuf/struct.proto";

option go_package = "cerence/cloudservices/domain/common/content/ude/v1";
option java_multiple_files = true;
option java_outer_classname = "PlaceProto";
option java_package = "com.cerence.cloudservices.domain.common.content.ude.v1";

// The type of the place. Possible values are as follows:
enum PlaceType {
  // No value has been specified.

  PLACE_TYPE_UNSPECIFIED = 0;
  // Used for return value only. Represents value unknown in this version.

  PLACE_TYPE_RESERVED_UNKNOWN = 1;
  PLACE_TYPE_POI = 2;
  PLACE_TYPE_ADDRESS = 3;
  PLACE_TYPE_BUILDING = 4;
}

message Place {

  // The name of the place.
  // If this place element was returned in response to a localsearch request, this element may not be included if a search for an address was requested.
  // For a response from what3words, this value is preceded by three slash marks (///).
  string name = 1;

  // The details of the location for the place.
  cerence.cloudservices.domain.common.content.common.v1.Location location = 2;

  // Container for one or more contact elements.
  repeated cerence.cloudservices.domain.common.content.common.v1.Contact contacts = 3;

  // Distance from the current location, as returned by the third party
  // provider. Units returned based on the value of the units parameter.
  cerence.cloudservices.domain.common.content.common.v1.Measurement distance = 4;

  // The details of the distance to this place, as calculated by cerence Cloud
  // Services.
  repeated cerence.cloudservices.domain.common.content.common.v1.Distance calculated_distances = 5;

  // Angle between the search center and the place, if available from the third
  // party provider. Positive integer 0-359. Due east is 0, north is 90. Only
  // returned if the geoPosition parameter was included in the request.
  int32 bearing = 6;

  // The bearing from the geoPosition sent in the request to the position of
  // this place, as calculated by cerence Cloud Services.
  int32 calculated_bearing = 7;

  // Container for one or more category elements.
  repeated cerence.cloudservices.domain.common.content.common.v1.Category categories = 8;

  // A token generated by the 3rd party broker.
  string place_id = 9;

  // The resource to report the user selection.
  cerence.cloudservices.domain.common.content.common.v1.Tracking tracking = 10;

  // The type of the place.
  PlaceType place_type = 11;

  // A container for the attribution details for this response.
  repeated cerence.cloudservices.domain.common.content.common.v1.Attribution attributions = 12;

  // Container for one or more accessPoint elements.
  repeated cerence.cloudservices.domain.common.content.common.v1.AccessPoint access_points = 13;

  // Container for the details of the operating days and hours for this place.
  cerence.cloudservices.domain.common.content.common.v1.OperatingHours operating_hours = 14;

  // Container for details about the place.
  Detail details = 15;

  message Detail {
    oneof payload {
      // Container for details about the place if the request is from the
      // localsearch/v3 service.
      LocalSearchDetail localsearch_detail = 1;

      // Container for details about the place if the request is from the
      // fuel/v2 service.
      FuelDetail fuel_detail = 2;

      // Container for details about the place if the request is from the
      // parking/v2 service.
      ParkingDetail parking_detail = 3;

      // Container for details about the place if the request is from the
      // evcharging/v2 service.
      EVChargingDetail evcharging_detail = 4 [json_name = "eVChargingDetail"];
    }
    // Details about the place normalized by the reasoning and knowledge engine.
    AiDetail ai_detail = 10;

    // Details about the visibility and geometry of the building or POI
    MultimodalDetail multimodal_detail = 11;

    // Details about the visibility and geometry of the building or POI
    WikiDetail wiki_detail = 12;

    // Details about the provider who could support reservation for the POI
    ReservationDetail reservation_detail = 13;

    // Details used for HERE MAP Data Products for core POI content
    CoreDetail core_detail = 14;
  }

  // Pronunciation for name field
  cerence.cloudservices.domain.common.content.common.v1.Pronunciation name_pronunciation = 16;

  // TTS description
  string tts = 17;

  // UDE response for HERE categories from the third party provider "As is"
  google.protobuf.Struct provider_pass_through = 18;

  // Container for one or more promotion details associated with this place
  repeated Promotion promotions = 19;

  // Container used to indicate if a business is operational, temporarily closed or permanently closed
  cerence.cloudservices.domain.common.content.common.v1.BusinessStatus business_status = 20;
}