// Copyright © 2025 Cerence Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the “Software”),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

syntax = "proto3";
package cerence.cloudservices.domain.common.content.ude.v1;

import "google/protobuf/timestamp.proto";

option go_package = "cerence/cloudservices/domain/common/content/ude/v1";
option java_multiple_files = true;
option java_outer_classname = "PromotionProto";
option java_package = "com.cerence.cloudservices.domain.common.content.ude.v1";

message Promotion {
  // A token generated by the third-party promotion provider.
  string promotion_id = 1;
  // A campaignId generated by the third-party promotion provider related to campaign.
  string campaign_id = 2;
  // A token generated by the third-party promotion provider related to particular POI.
  string promotion_poi_id = 3;
  // The expiration date and time of the promotion in ISO 8601 format: YYYY-MM-DDThh:mm:ssZ (e.g., 2025-12-31T23:59:59Z)
  google.protobuf.Timestamp expiration_date = 4;
  // The currency used for the promotion, following ISO 4217 format (3-letter uppercase code). e.g. USD, EUR, INR
  string currency = 5;
  // Container for one or more offer details elements for this promotion.
  repeated OfferDetail offer_details = 6;
}

message OfferDetail{
  // A type associated with ad format
  PromotionAdFormat ad_format = 1;
  // Offer language in ISO 639-1 format (e.g., en, de, fr, hi)
  string language = 2;
  // The offer content to be displayed on HU.
  OfferContent offer_content = 3;
}

message OfferContent{
  // A detailed description of the offer for display on HU
  string description = 1;
  // A headline of the offer for display on HU
  string headline = 2;
  // A URL (HTTPS) for a brand logo that features offers.
  string brand_logo_url = 3;
  // An image URL (HTTPS) containing offer details.
  string offer_image_url = 4;
}

// The description of the PromotionAdFormat used to show offer details screen.
// Possible values are as follows:
enum PromotionAdFormat {
  // No value has been specified.
  PROMOTION_AD_FORMAT_UNSPECIFIED = 0;
  // Used for return value only
  PROMOTION_AD_FORMAT_DETAIL_SCREEN = 1;
  PROMOTION_AD_FORMAT_SEARCH_SCREEN = 2;

}