// Copyright © 2022 Cerence Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the “Software”),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

syntax = "proto3";

package cerence.cloudservices.domain.common.content.ude.v1;


option go_package = "cerence/cloudservices/domain/common/content/ude/v1";
option java_multiple_files = true;
option java_outer_classname = "ProvenanceProto";
option java_package = "com.cerence.cloudservices.domain.common.content.ude.v1";

message Provenance {
  option deprecated = true;
  enum Reasoner {
    option deprecated = true;
    // No value has been specified.
    REASONER_UNSPECIFIED = 0;

    // Used for return value only. Represents value unknown in this
    // version.
    REASONER_RESERVED_UNKNOWN = 1;

    // Along the path reasoner
    REASONER_ALONG_THE_PATH = 2;

    // Local search reasoner
    REASONER_SMART_LOCALSEARCH = 3;

    // Fuel reasoner
    REASONER_SMART_FUEL = 4;

    // Parking reasoner
    REASONER_SMART_PARKING = 5;

    // Restaurant reasoner
    REASONER_SMARTRESTAURANT = 6;

    // Electic vehicule reasoner
    REASONER_SMART_EV_CHARGING = 7;
  }

  Reasoner reasoner = 1;

  int32 depth = 2;

  repeated Inference inferences = 3;

  repeated RuleId rule_ids = 4;

  repeated Preference user_preferences = 5;
}

enum Preference {
  option deprecated = true;
  // No value has been specified.
  PREFERENCE_UNSPECIFIED = 0;

  // Used for return value only. Represents value unknown in this
  // version.
  PREFERENCE_RESERVED_UNKNOWN = 1;

  // Smart Fuel
  PREFERENCE_FUEL_BRAND = 10;
  PREFERENCE_FUEL_PRICE = 11;
  PREFERENCE_FUEL_TYPE = 12;

  // Smart Parking
  PREFERENCE_PARKING_CATEGORY = 20;
  PREFERENCE_PARKING_PRICE = 21;

  // Smart Local Search
  PREFERENCE_LOCALSEARCH_PRICE = 30;
  PREFERENCE_LOCALSEARCH_CATEGORY = 31;
  PREFERENCE_LOCALSEARCH_BRAND = 32;
  PREFERENCE_LOCALSEARCH_QUALITY = 33;

  // Smart Restaurant
  PREFERENCE_RESTAURANT_CATEGORY = 40;
  PREFERENCE_RESTAURANT_BRAND = 41;
  PREFERENCE_RESTAURANT_PRICE = 42;
  PREFERENCE_RESTAURANT_QUALITY = 43;

  // Smart Electric Vehicle Charging
  PREFERENCE_EV_SERVICE_PROVIDER_BRAND = 50;
  PREFERENCE_EV_SERVICE_OPERATOR_BRAND = 51;
}

enum RuleId {
  option deprecated = true;
  // No value has been specified.
  RULE_ID_UNSPECIFIED = 0;

  // Used for return value only. Represents value unknown in this
  // version.
  RULE_ID_RESERVED_UNKNOWN = 1;

  RULE_ID_DDISCV3_PARKING_CAR_HEIGHT = 100;
  RULE_ID_DDISCV3_PARKING_ELECTRIC_VEHICLE = 101;
  RULE_ID_DDISCV4_PARKING_WEATHER_DISABLED_1 = 102;
  RULE_ID_DDISCV4_PARKING_WEATHER_DISABLED_2 = 103;
  RULE_ID_DDISCV4_PARKING_WEATHER_CLOSEST = 104;
  RULE_ID_DDISCV4_PARKING_WEATHER_CLOSEST_UNBOUND = 105;
  RULE_ID_DDISCV3_PARKING_PAYMENT_METHOD = 106;
  RULE_ID_DDISCV3_PARKING_ETA_GEO = 107;
  RULE_ID_DDISCV3_FUEL_FUEL_TYPE = 108;
  RULE_ID_DDISCV3_FUEL_FUEL_BRAND = 109;
  RULE_ID_DDISCV3_FUEL_PREFER_SORT_BY_PRICE = 110;
  RULE_ID_DDISCV4_FUEL_CONTEXT_CURRENT_TIME = 111;
  RULE_ID_DDISCV3_FUEL_SEARCH_RADIUS_ZERO_RANGE = 112;
  RULE_ID_DDISCV3_FUEL_SEARCH_RADIUS_NEARBY = 113;
  RULE_ID_DDISCV4_BIZ_BRAND_PREFERENCE_BANK = 114;
  RULE_ID_DDISCV4_BIZ_BRAND_PREFERENCE_GROCERY = 115;
  RULE_ID_DDISCV4_BIZ_BRAND_PREFERENCE_COFFEE = 116;
  RULE_ID_DDISCV4_BIZ_BRAND_PREFERENCE_STORE = 117;
  RULE_ID_DDISCV4_BIZ_BRAND_PREFERENCE_PHARMACY = 118;
  RULE_ID_DDISCV4_BIZ_CNTXT_CURRENT_TIME = 119;
  RULE_ID_DDISCV4_BIZ_ETA_GEO = 120;
  RULE_ID_DDISCV4_BIZ_SEARCH_RADIUS = 121;
  RULE_ID_DDISCV4_BIZ_LEX_TO_BRAND = 122;
  RULE_ID_DDISCV4_BIZ_NEED_RESTROOM = 123;
  RULE_ID_DDISCV4_BIZ_NEED_FLOWERS_AFTER_5 = 124;
  RULE_ID_DDISCV4_BIZ_NEED_FLOWERS_BEFORE_5 = 125;
  RULE_ID_DDISCV4_BIZ_NEED_GROCERY = 126;
  RULE_ID_DDISCV4_BIZ_NEED_PLAY = 127;
  RULE_ID_DDISCV4_BIZ_NEED_REST_NIGHT = 128;
  RULE_ID_DDISCV4_BIZ_NEED_REST_DAY = 129;

  RULE_ID_SMART_EVCHARGING_PROVIDER_PREFERENCE = 200;
  RULE_ID_SMART_EVCHARGING_OPERATOR_PREFERENCE = 201;
  RULE_ID_SMART_EVCHARGING_PLUGTYPE_CONTEXT = 202;
  RULE_ID_SMART_EVCHARGING_RANGE = 203;
  RULE_ID_SMART_EVCHARGING_PLUGTYPE_DEFAULT = 204;

  RULE_ID_SMART_FUEL_FUEL_TYPE = 300;
  RULE_ID_SMART_FUEL_FUEL_BRAND = 301;
  RULE_ID_SMART_FUEL_PRICE_PREFERENCE_SORT_STEP1 = 302;
  RULE_ID_SMART_FUEL_PRICE_PREFERENCE_SORT_STEP2 = 303;
  RULE_ID_SMART_FUEL_PRICE_PREFERENCE_EXPENSIVE = 304;
  RULE_ID_SMART_FUEL_DISTANCE_PREFERENCE_SORT_STEP1 = 305;
  RULE_ID_SMART_FUEL_DISTANCE_PREFERENCE_STEP2 = 306;
  RULE_ID_SMART_FUEL_PROXIMITY_PREFERENCE = 307;
  RULE_ID_SMART_FUEL_CONTEXT_CURRENT_TIME = 308;
  RULE_ID_SMART_FUEL_ETA_DATETIME_LOC = 309;
  RULE_ID_SMART_FUEL_ETA_DATETIME_DEST = 310;
  RULE_ID_DDISCV3_FUEL_ETA_GEO = 311;
  RULE_ID_SMART_FUEL_FUEL_RANGE = 312;
  RULE_ID_SMART_FUEL_PENALIZE_CLOSED = 313;
  RULE_ID_SMART_FUEL_ENABLE_DEFAULT_OPEN_STATUS_PROMOTION = 314;

  RULE_ID_SMART_LOCALSEARCH_BRAND_PREFERENCE = 400;
  RULE_ID_SMART_LOCALSEARCH_SORT_PREFERENCE_PRICE = 401;
  RULE_ID_SMART_LOCALSEARCH_SORT_PREFERENCE_QUALITY = 402;
  RULE_ID_SMART_LOCALSEARCH_SORT_PREFERENCE_DISTANCE = 403;
  RULE_ID_SMART_LOCALSEARCH_PRICE_PREFERENCE_STEP1 = 404;
  RULE_ID_SMART_LOCALSEARCH_PRICE_PREFERENCE_STEP2 = 405;
  RULE_ID_SMART_LOCALSEARCH_PRICE_PREFERENCE_EXPENSIVE = 406;
  RULE_ID_SMART_LOCALSEARCH_QUALITY_PREFERENCE_STEP1 = 407;
  RULE_ID_SMART_LOCALSEARCH_QUALITY_PREFERENCE_STEP2 = 408;
  RULE_ID_SMART_LOCALSEARCH_DISTANCE_PREFERENCE_STEP1 = 409;
  RULE_ID_SMART_LOCALSEARCH_DISTANCE_PREFERENCE_STEP2 = 410;
  RULE_ID_SMART_LOCALSEARCH_PROXIMITY_PREFERENCE = 411;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_COST_CHEAP = 412;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_COST_MODERATE = 413;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_COST_EXPENSIVE = 414;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_QUALITY_EXCELLENT = 415;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_QUALITY_VERY_GOOD = 416;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_QUALITY_GOOD = 417;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_QUALITY_AVERAGE = 418;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_QUALITY_POOR = 419;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_POPULARITY_POPULAR = 420;
  RULE_ID_SMART_LOCALSEARCH_THRESHOLD_POPULARITY_MEDIUM = 421;
  RULE_ID_SMART_LOCALSEARCH_CONTEXT_CURRENT_TIME = 422;
  RULE_ID_SMART_LOCALSEARCH_ETA_DATETIME_LOC = 423;
  RULE_ID_SMART_LOCALSEARCH_ETA_DATETIME_DEST = 424;
  RULE_ID_SMART_LOCALSEARCH_ETA_GEO = 425;
  RULE_ID_SMART_LOCALSEARCH_RADIUS_LOCATION = 426;
  RULE_ID_SMART_LOCALSEARCH_DEFAULT_RADIUS_CATEGORY = 427;
  RULE_ID_SMART_LOCALSEARCH_DEFAULT_RADIUS = 428;
  RULE_ID_SMART_LOCALSEARCH_LEX_TO_BRAND_GENERIC = 429;
  RULE_ID_SMART_LOCALSEARCH_LEX_TO_BRAND_GENERIC_WITH_CATEGORY = 430;
  RULE_ID_SMART_LOCALSEARCH_LEX_TO_BRAND_SORT = 431;
  RULE_ID_SMART_LOCALSEARCH_LEX_TO_BRAND = 432;
  RULE_ID_SMART_LOCALSEARCH_PENALIZE_CLOSED = 433;
  RULE_ID_SMART_LOCALSEARCH_POI_ONESHOT = 434;
  RULE_ID_SMART_LOCALSEARCH_POI_ALTERNATIVES_ONESHOT = 435;
  RULE_ID_SMART_LOCALSEARCH_ANCHOR_ONESHOT = 436;
  RULE_ID_SMART_LOCALSEARCH_POI_ONESHOT_ASSERT = 437;
  RULE_ID_SMART_LOCALSEARCH_POI_ALTERNATIVES_ONESHOT_ASSERT = 438;
  RULE_ID_SMART_LOCALSEARCH_ANCHOR_ONESHOT_ASSERT = 439;
  RULE_ID_SMART_LOCALSEARCH_POI_ONESHOT_CHINA = 440;
  RULE_ID_SMART_LOCALSEARCH_ENABLE_DEFAULT_RADIUS = 441;
  RULE_ID_SMART_LOCALSEARCH_ENABLE_DEFAULT_LEX_TO_BRAND = 442;
  RULE_ID_SMART_LOCALSEARCH_ENABLE_DEFAULT_OPEN_STATUS_PROMOTION = 443;
  RULE_ID_SMART_LOCALSEARCH_DISABLE_DEFAULT_ONESHOT_LOCATION = 444;
  RULE_ID_SMART_LOCALSEARCH_ENABLE_DEFAULT_ONESHOT_LOCATION_CHINA = 445;
  RULE_ID_SMART_LOCALSEARCH_DISABLE_DEFAULT_ONESHOT_LOCATION_WORKAROUND = 446;
  RULE_ID_SMART_LOCALSEARCH_ENABLE_DEFAULT_ONESHOT_LOCATION_CHINA_WORKAROUND = 447;

  RULE_ID_SMART_LOCALSEARCH_RADIUS_MULTIMODAL = 500;
  RULE_ID_SMART_LOCALSEARCH_MULTIMODAL_UNMAPPEDCATEGORY = 501;

  RULE_ID_SMART_LOCALSEARCH_PRODUCT_REASONING = 600;
  RULE_ID_SMART_LOCALSEARCH_PRODUCT_REGIONAL_REASONING = 601;
  RULE_ID_WANT_FLOWERS_QUA_FRESHCUTFLOWER_6PM_TO_9AM = 602;
  RULE_ID_WANT_FLOWERS_QUA_FRESHCUTFLOWER = 603;

  RULE_ID_SMART_PARKING_CAR_HEIGHT = 700;
  RULE_ID_SMART_PARKING_ELECTRIC_VEHICLE = 701;
  RULE_ID_SMART_PARKING_DISABILITY = 702;
  RULE_ID_SMART_PARKING_DISABILITY_ELEVATOR = 703;
  RULE_ID_SMART_PARKING_WOMEN_PARKING = 704;
  RULE_ID_SMART_PARKING_WEATHER_DISABLED = 705;
  RULE_ID_SMART_PARKING_SORT_PREFERENCE = 706;
  RULE_ID_SMART_PARKING_PROXIMITY_PREFERENCE = 707;
  RULE_ID_SMART_PARKING_PRICE_PREFERENCE_SORT_STEP1 = 708;
  RULE_ID_SMART_PARKING_PRICE_PREFERENCE_SORT_STEP2 = 709;
  RULE_ID_SMART_PARKING_PRICE_PREFERENCE_EXPENSIVE = 710;
  RULE_ID_SMART_PARKING_PRICE_PREFERENCE_FALLBACK = 711;
  RULE_ID_SMART_PARKING_DISTANCE_PREFERENCE_SORT_STEP1 = 712;
  RULE_ID_SMART_PARKING_DISTANCE_PREFERENCE_STEP2 = 713;
  RULE_ID_SMART_PARKING_CATEGORY_PREFERENCE = 714;
  RULE_ID_SMART_PARKING_PENALIZE_CLOSED = 715;
  RULE_ID_SMART_PARKING_ENABLE_DEFAULT_OPEN_STATUS_PROMOTION = 716;

  RULE_ID_SMART_RESTAURANT_CATEGORY_PREFERENCE = 800;
  RULE_ID_SMART_RESTAURANT_BRAND_PREFERENCE = 801;
  RULE_ID_SMART_RESTAURANT_SORT_PREFERENCE_PRICE = 802;
  RULE_ID_SMART_RESTAURANT_SORT_PREFERENCE_QUALITY = 803;
  RULE_ID_SMART_RESTAURANT_SORT_PREFERENCE_DISTANCE = 804;
  RULE_ID_SMART_RESTAURANT_PRICE_PREFERENCE_STEP1 = 805;
  RULE_ID_SMART_RESTAURANT_PRICE_PREFERENCE_STEP2 = 806;
  RULE_ID_SMART_RESTAURANT_PRICE_PREFERENCE_EXPENSIVE = 807;
  RULE_ID_SMART_RESTAURANT_QUALITY_PREFERENCE_STEP1 = 808;
  RULE_ID_SMART_RESTAURANT_QUALITY_PREFERENCE_STEP2 = 809;
  RULE_ID_SMART_RESTAURANT_DISTANCE_PREFERENCE_STEP1 = 810;
  RULE_ID_SMART_RESTAURANT_DISTANCE_PREFERENCE_STEP2 = 811;
  RULE_ID_SMART_RESTAURANT_PROXIMITY_PREFERENCE = 812;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_COST_CHEAP = 813;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_COST_MODERATE = 814;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_COST_EXPENSIVE = 815;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_QUALITY_EXCELLENT = 816;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_QUALITY_VERY_GOOD = 817;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_QUALITY_GOOD = 818;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_QUALITY_AVERAGE = 819;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_QUALITY_POOR = 820;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_POPULARITY_POPULAR = 821;
  RULE_ID_SMART_RESTAURANT_THRESHOLD_POPULARITY_MEDIUM = 822;
  RULE_ID_SMART_RESTAURANT_CONTEXT_CURRENT_TIME = 823;
  RULE_ID_SMART_RESTAURANT_ETA_DATETIME_LOC = 824;
  RULE_ID_SMART_RESTAURANT_ETA_DATETIME_DEST = 825;
  RULE_ID_SMART_RESTAURANT_ETA_GEO = 826;
  RULE_ID_SMART_RESTAURANT_RADIUS_LOCATION = 827;
  RULE_ID_SMART_RESTAURANT_DEFAULT_RADIUS = 828;
  RULE_ID_SMART_RESTAURANT_LEX_TO_BRAND_GENERIC = 829;
  RULE_ID_SMART_RESTAURANT_LEX_TO_BRAND_GENERIC_WITH_CATEGORY = 830;
  RULE_ID_SMART_RESTAURANT_LEX_TO_BRAND_GENERIC_WITH_BRANDTYPE = 831;
  RULE_ID_SMART_RESTAURANT_LEX_TO_BRAND_SORT = 832;
  RULE_ID_SMART_RESTAURANT_LEX_TO_BRAND = 833;
  RULE_ID_SMART_RESTAURANT_CHAIN_BACKOFF_LEX_TO_BRAND = 834;
  RULE_ID_SMART_RESTAURANT_PENALIZE_CLOSED = 835;
  RULE_ID_SMART_RESTAURANT_POI_ONESHOT = 836;
  RULE_ID_SMART_RESTAURANT_POI_ALTERNATIVES_ONESHOT = 837;
  RULE_ID_SMART_RESTAURANT_ANCHOR_ONESHOT = 838;
  RULE_ID_SMART_RESTAURANT_POI_ONESHOT_ASSERT = 839;
  RULE_ID_SMART_RESTAURANT_POI_ALTERNATIVES_ONESHOT_ASSERT = 840;
  RULE_ID_SMART_RESTAURANT_ANCHOR_ONESHOT_ASSERT = 841;
  RULE_ID_SMART_RESTAURANT_POI_ONESHOT_CHINA = 842;
  RULE_ID_SMART_RESTAURANT_ENABLE_DEFAULT_RADIUS = 843;
  RULE_ID_SMART_RESTAURANT_ENABLE_DEFAULT_LEX_TO_BRAND = 844;
  RULE_ID_SMART_RESTAURANT_ENABLE_DEFAULT_OPEN_STATUS_PROMOTION = 845;
  RULE_ID_SMART_RESTAURANT_DISABLE_DEFAULT_ONESHOT_LOCATION = 846;
  RULE_ID_SMART_RESTAURANT_ENABLE_DEFAULT_ONESHOT_LOCATION_CHINA = 847;

  RULE_ID_SMART_RESTAURANT_INFER_MARKET = 900;
  RULE_ID_SMART_RESTAURANT_DISH_REASONING = 901;
  RULE_ID_SMART_RESTAURANT_CUISINE_SIMILARITY_REASONING = 902;
  RULE_ID_SMART_RESTAURANT_BRAND_SIMILARITY_REASONING = 903;
  RULE_ID_SMART_RESTAURANT_BRAND_NAME = 904;
  RULE_ID_SMART_RESTAURANT_NEG_BRAND_NAME = 905;
  RULE_ID_SMART_RESTAURANT_BRAND_CATEGORY_FALLBACK = 906;
  RULE_ID_SMART_RESTAURANT_ENABLE_DEFAULT_BRAND_SIMILARITY = 907;
  RULE_ID_SMART_RESTAURANT_ENABLE_DEFAULT_CUISINE_SIMILARITY = 908;

  RULE_ID_SMART_RESTAURANT_RADIUS_MULTIMODAL = 1000;
  RULE_ID_SMART_RESTAURANT_MULTIMODAL_UNMAPPEDCATEGORY = 1001;
}

message Inference {
  option deprecated = true;
  RuleId rule_id = 1;

  repeated Assertion assertions = 2;

  repeated Assertion retractions = 3;
}

enum Operator {
  // No value has been specified.
  OPERATOR_UNSPECIFIED = 0;

  // Used for return value only. Represents value unknown in this
  // version.
  OPERATOR_RESERVED_UNKNOWN = 1;

  OPERATOR_NOT_EQUAL = 2;
  OPERATOR_LESS_THAN_OR_EQUAL = 3;
  OPERATOR_GREATER_THAN_OR_EQUAL = 4;
  OPERATOR_EQUALS = 5;
  OPERATOR_GREATER_THAN = 6;
  OPERATOR_LESS_THAN = 7;
}

message Assertion {
  option deprecated = true;
  enum SemanticRelations {
    // No value has been specified.
    SEMANTIC_RELATIONS_UNSPECIFIED = 0;

    // Used for return value only. Represents value unknown in this
    // version.
    SEMANTIC_RELATIONS_RESERVED_UNKNOWN = 1;

    SEMANTIC_RELATIONS_CHARGING_OFFER_PLUG_TYPE = 2;
  }

  // The semantic relations part of this assertion
  repeated SemanticRelations semantic_relations = 1;

  enum ResultVariables {
    // No value has been specified.
    RESULT_VARIABLES_UNSPECIFIED = 0;

    // Used for return value only. Represents value unknown in this
    // version.
    RESULT_VARIABLES_RESERVED_UNKNOWN = 1;

    RESULT_VARIABLES_NAME = 2;

    // Local search and restaurant
    RESULT_VARIABLES_BRAND_NAME = 10;

    RESULT_VARIABLES_AMENITIES = 11;
    RESULT_VARIABLES_STATUS = 12;
    RESULT_VARIABLES_OPERATING_HOURS = 13;
    RESULT_VARIABLES_COST = 14;
    RESULT_VARIABLES_DISTANCE = 15;
    RESULT_VARIABLES_PAYMENT_TYPE = 16;
    RESULT_VARIABLES_CATEGORY = 17;
    RESULT_VARIABLES_PROVIDER_RATING = 18;
    RESULT_VARIABLES_RATING = 19;

    // Fuel
    RESULT_VARIABLES_FUEL_TYPE = 30;
    RESULT_VARIABLES_FUEL_PRICE = 31;

    //Parking
    RESULT_VARIABLES_PARKING_TYPE = 50;
    RESULT_VARIABLES_PARKING_CATEGORY = 51;
    RESULT_VARIABLES_PARKING_ENTRANCE_HEIGHT = 52;
    RESULT_VARIABLES_PARKING_AVAILABILITY = 53;
    RESULT_VARIABLES_PARKING_COST_RATE = 54;

    //EV Charging
    RESULT_VARIABLES_CHARGING_OFFER_PLUG_TYPE = 70;
    RESULT_VARIABLES_CHARGING_PROVIDER = 71;
    RESULT_VARIABLES_CHARGING_OPERATOR = 72;
  }

  // The variable on which the assertion was applied
  ResultVariables result_variable = 2;

  message Values {

    string value = 1;

    Operator operator = 2;

    bool relaxable = 3;
  }

  Values values = 3;
}

