# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/dialog/v1/dialog_streaming_response_payload.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/dialog/v1/dialog_streaming_response_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nUcerence/cloudservices/domain/common/dialog/v1/dialog_streaming_response_payload.proto\x12-cerence.cloudservices.domain.common.dialog.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xd6\x01\n\nFacetChunk\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x03 \x01(\x0cH\x00\x12/\n\x0cstruct_value\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x12Q\n\nchunk_info\x18\x05 \x01(\x0b\x32=.cerence.cloudservices.domain.common.dialog.v1.FacetChunkInfoB\x07\n\x05value\"B\n\x0e\x46\x61\x63\x65tChunkInfo\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x05\x12\x1f\n\x17is_last_for_interaction\x18\x02 \x01(\x08\")\n\x0e\x44ialogFollowUp\x12\x17\n\x0fhas_active_task\x18\x01 \x01(\x08\x42\x84\x01\n1com.cerence.cloudservices.domain.common.dialog.v1B\x1e\x44ialogStreamingResponsePayloadP\x01Z-cerence/cloudservices/domain/common/dialog/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.dialog.v1.dialog_streaming_response_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.cerence.cloudservices.domain.common.dialog.v1B\036DialogStreamingResponsePayloadP\001Z-cerence/cloudservices/domain/common/dialog/v1'
  _globals['_FACETCHUNK']._serialized_start=167
  _globals['_FACETCHUNK']._serialized_end=381
  _globals['_FACETCHUNKINFO']._serialized_start=383
  _globals['_FACETCHUNKINFO']._serialized_end=449
  _globals['_DIALOGFOLLOWUP']._serialized_start=451
  _globals['_DIALOGFOLLOWUP']._serialized_end=492
# @@protoc_insertion_point(module_scope)
