# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/dialog/v1/dialog_query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/dialog/v1/dialog_query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@cerence/cloudservices/domain/common/dialog/v1/dialog_query.proto\x12-cerence.cloudservices.domain.common.dialog.v1\"d\n\x0cQueryRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x43\n\x05query\x18\x02 \x01(\x0b\x32\x34.cerence.cloudservices.domain.common.dialog.v1.Query\"{\n\x05Query\x12\x10\n\x08query_id\x18\x01 \x01(\r\x12\x15\n\rquery_concept\x18\x02 \x01(\t\x12I\n\x08\x63riteria\x18\x03 \x01(\x0b\x32\x37.cerence.cloudservices.domain.common.dialog.v1.Criteria\"T\n\x08\x43riteria\x12H\n\x08\x63oncepts\x18\x01 \x03(\x0b\x32\x36.cerence.cloudservices.domain.common.dialog.v1.Concept\"j\n\x07\x43oncept\x12\x14\n\x0c\x63oncept_name\x18\x01 \x01(\t\x12I\n\x05items\x18\x02 \x03(\x0b\x32:.cerence.cloudservices.domain.common.dialog.v1.ConceptItem\"-\n\x0b\x43onceptItem\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07literal\x18\x02 \x01(\tBv\n1com.cerence.cloudservices.domain.common.dialog.v1B\x10\x44ialogQueryProtoP\x01Z-cerence/cloudservices/domain/common/dialog/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.dialog.v1.dialog_query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.cerence.cloudservices.domain.common.dialog.v1B\020DialogQueryProtoP\001Z-cerence/cloudservices/domain/common/dialog/v1'
  _globals['_QUERYREQUEST']._serialized_start=115
  _globals['_QUERYREQUEST']._serialized_end=215
  _globals['_QUERY']._serialized_start=217
  _globals['_QUERY']._serialized_end=340
  _globals['_CRITERIA']._serialized_start=342
  _globals['_CRITERIA']._serialized_end=426
  _globals['_CONCEPT']._serialized_start=428
  _globals['_CONCEPT']._serialized_end=534
  _globals['_CONCEPTITEM']._serialized_start=536
  _globals['_CONCEPTITEM']._serialized_end=581
# @@protoc_insertion_point(module_scope)
