# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/dialog/v1/dialog_interaction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/dialog/v1/dialog_interaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFcerence/cloudservices/domain/common/dialog/v1/dialog_interaction.proto\x12-cerence.cloudservices.domain.common.dialog.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe8\x01\n\x0bInteraction\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12V\n\x06\x66\x61\x63\x65ts\x18\x03 \x03(\x0b\x32\x46.cerence.cloudservices.domain.common.dialog.v1.Interaction.FacetsEntry\x1a\x63\n\x0b\x46\x61\x63\x65tsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x43\n\x05value\x18\x02 \x01(\x0b\x32\x34.cerence.cloudservices.domain.common.dialog.v1.Facet:\x02\x38\x01\"\x95\x01\n\x05\x46\x61\x63\x65t\x12\x12\n\nescalation\x18\x01 \x01(\r\x12\x0f\n\x07variant\x18\x02 \x01(\r\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x04 \x01(\x0cH\x00\x12/\n\x0cstruct_value\x18\x05 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x42\x07\n\x05valueBv\n1com.cerence.cloudservices.domain.common.dialog.v1B\x10InteractionProtoP\x01Z-cerence/cloudservices/domain/common/dialog/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.dialog.v1.dialog_interaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.cerence.cloudservices.domain.common.dialog.v1B\020InteractionProtoP\001Z-cerence/cloudservices/domain/common/dialog/v1'
  _globals['_INTERACTION_FACETSENTRY']._loaded_options = None
  _globals['_INTERACTION_FACETSENTRY']._serialized_options = b'8\001'
  _globals['_INTERACTION']._serialized_start=152
  _globals['_INTERACTION']._serialized_end=384
  _globals['_INTERACTION_FACETSENTRY']._serialized_start=285
  _globals['_INTERACTION_FACETSENTRY']._serialized_end=384
  _globals['_FACET']._serialized_start=387
  _globals['_FACET']._serialized_end=536
# @@protoc_insertion_point(module_scope)
