# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/dialog/v1/dialog_task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/dialog/v1/dialog_task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?cerence/cloudservices/domain/common/dialog/v1/dialog_task.proto\x12-cerence.cloudservices.domain.common.dialog.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa1\x03\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06intent\x18\x02 \x01(\t\x12\x0f\n\x07literal\x18\x03 \x01(\t\x12H\n\x05state\x18\x04 \x01(\x0e\x32\x39.cerence.cloudservices.domain.common.dialog.v1.Task.State\x12Q\n\x07\x63ontext\x18\x05 \x03(\x0b\x32@.cerence.cloudservices.domain.common.dialog.v1.Task.ContextEntry\x12\x19\n\x11\x63oncepts_in_focus\x18\x06 \x03(\t\x1a\x46\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\"l\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTATE_ACTIVE\x10\x01\x12\x13\n\x0fSTATE_SUSPENDED\x10\x02\x12\x12\n\x0eSTATE_FINISHED\x10\x03\x12\x11\n\rSTATE_ABORTED\x10\x04\x42u\n1com.cerence.cloudservices.domain.common.dialog.v1B\x0f\x44ialogTaskProtoP\x01Z-cerence/cloudservices/domain/common/dialog/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.dialog.v1.dialog_task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.cerence.cloudservices.domain.common.dialog.v1B\017DialogTaskProtoP\001Z-cerence/cloudservices/domain/common/dialog/v1'
  _globals['_TASK_CONTEXTENTRY']._loaded_options = None
  _globals['_TASK_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_TASK']._serialized_start=145
  _globals['_TASK']._serialized_end=562
  _globals['_TASK_CONTEXTENTRY']._serialized_start=382
  _globals['_TASK_CONTEXTENTRY']._serialized_end=452
  _globals['_TASK_STATE']._serialized_start=454
  _globals['_TASK_STATE']._serialized_end=562
# @@protoc_insertion_point(module_scope)
