# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/services/user_data/v1/diagnostic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@cerence/cloudservices/api/services/user_data/v1/diagnostic.proto\x12/cerence.cloudservices.api.services.user_data.v1\"9\n\x15\x44iagnosticInformation\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04\x66qdn\x18\x02 \x01(\tBt\n3com.cerence.cloudservices.api.services.user_data.v1B\nDiagnosticP\x01Z/cerence/cloudservices/api/services/user_data/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.user_data.v1.diagnostic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n3com.cerence.cloudservices.api.services.user_data.v1B\nDiagnosticP\001Z/cerence/cloudservices/api/services/user_data/v1'
  _DIAGNOSTICINFORMATION._serialized_start=117
  _DIAGNOSTICINFORMATION._serialized_end=174
# @@protoc_insertion_point(module_scope)
