# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/services/user_data/v1/input_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@cerence/cloudservices/api/services/user_data/v1/input_data.proto\x12/cerence.cloudservices.api.services.user_data.v1\"\xbb\x01\n\tDataBlock\x12M\n\x08\x63ontacts\x18\x01 \x01(\x0b\x32\x39.cerence.cloudservices.api.services.user_data.v1.ContactsH\x00\x12T\n\x0c\x63ustom_words\x18\x02 \x01(\x0b\x32<.cerence.cloudservices.api.services.user_data.v1.CustomWordsH\x00\x42\t\n\x07payload\"U\n\x08\x43ontacts\x12I\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x38.cerence.cloudservices.api.services.user_data.v1.Contact\"\xef\x01\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x1b\n\x13\x66irst_name_phonetic\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x1a\n\x12last_name_phonetic\x18\x05 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x06 \x01(\t\x12\x11\n\tfull_name\x18\x07 \x01(\t\x12\x11\n\tnick_name\x18\x08 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\t \x01(\t\x12\x11\n\tproviders\x18\n \x03(\t\x12\x14\n\x0crelationship\x18\x0b \x01(\t\"[\n\x0b\x43ustomWords\x12L\n\x07\x65ntries\x18\x01 \x03(\x0b\x32;.cerence.cloudservices.api.services.user_data.v1.CustomWord\"\'\n\nCustomWord\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\tBx\n3com.cerence.cloudservices.api.services.user_data.v1B\x0eInputDataProtoP\x01Z/cerence/cloudservices/api/services/user_data/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.user_data.v1.input_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n3com.cerence.cloudservices.api.services.user_data.v1B\016InputDataProtoP\001Z/cerence/cloudservices/api/services/user_data/v1'
  _DATABLOCK._serialized_start=118
  _DATABLOCK._serialized_end=305
  _CONTACTS._serialized_start=307
  _CONTACTS._serialized_end=392
  _CONTACT._serialized_start=395
  _CONTACT._serialized_end=634
  _CUSTOMWORDS._serialized_start=636
  _CUSTOMWORDS._serialized_end=727
  _CUSTOMWORD._serialized_start=729
  _CUSTOMWORD._serialized_end=768
# @@protoc_insertion_point(module_scope)
