# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/services/user_data/v1/user_data_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEcerence/cloudservices/api/services/user_data/v1/user_data_types.proto\x12/cerence.cloudservices.api.services.user_data.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xc8\x01\n\x0bRequestData\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x17\n\nconcept_id\x18\x03 \x01(\tB\x03\xe0\x41\x02\x12\x62\n\x14product_improvements\x18\x04 \x01(\x0b\x32\x44.cerence.cloudservices.api.services.user_data.v1.ProductImprovements\x12\x18\n\x10response_version\x18\x05 \x01(\t\"&\n\nUploadDone\x12\x18\n\x0bnew_version\x18\x01 \x01(\x05\x42\x03\xe0\x41\x02\"M\n\x13ProductImprovements\x12\x36\n\x12model_improvements\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\"\x93\x01\n\tDeleteAll\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x62\n\x14product_improvements\x18\x03 \x01(\x0b\x32\x44.cerence.cloudservices.api.services.user_data.v1.ProductImprovementsB|\n3com.cerence.cloudservices.api.services.user_data.v1B\x12UserDataTypesProtoP\x01Z/cerence/cloudservices/api/services/user_data/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.user_data.v1.user_data_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n3com.cerence.cloudservices.api.services.user_data.v1B\022UserDataTypesProtoP\001Z/cerence/cloudservices/api/services/user_data/v1'
  _REQUESTDATA.fields_by_name['concept_id']._options = None
  _REQUESTDATA.fields_by_name['concept_id']._serialized_options = b'\340A\002'
  _UPLOADDONE.fields_by_name['new_version']._options = None
  _UPLOADDONE.fields_by_name['new_version']._serialized_options = b'\340A\002'
  _REQUESTDATA._serialized_start=188
  _REQUESTDATA._serialized_end=388
  _UPLOADDONE._serialized_start=390
  _UPLOADDONE._serialized_end=428
  _PRODUCTIMPROVEMENTS._serialized_start=430
  _PRODUCTIMPROVEMENTS._serialized_end=507
  _DELETEALL._serialized_start=510
  _DELETEALL._serialized_end=657
# @@protoc_insertion_point(module_scope)
