# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/services/asr/v1/format_word.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/services/asr/v1/format_word.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.api.services.asr.v1 import spoken_form_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_asr_dot_v1_dot_spoken__form__pb2
from cerence.cloudservices.api.services.asr.v1 import word_info_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_asr_dot_v1_dot_word__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;cerence/cloudservices/api/services/asr/v1/format_word.proto\x12)cerence.cloudservices.api.services.asr.v1\x1a;cerence/cloudservices/api/services/asr/v1/spoken_form.proto\x1a\x39\x63\x65rence/cloudservices/api/services/asr/v1/word_info.proto\"\xc6\x01\n\nFormatWord\x12S\n\x10word_spoken_form\x18\x01 \x01(\x0b\x32\x39.cerence.cloudservices.api.services.asr.v1.WordSpokenForm\x12\x11\n\x07literal\x18\x02 \x01(\tH\x00\x12H\n\tword_info\x18\x03 \x01(\x0b\x32\x33.cerence.cloudservices.api.services.asr.v1.WordInfoH\x00\x42\x06\n\x04wordBm\n-com.cerence.cloudservices.api.services.asr.v1B\x0f\x46ormatWordProtoP\x01Z)cerence/cloudservices/api/services/asr/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.asr.v1.format_word_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.cerence.cloudservices.api.services.asr.v1B\017FormatWordProtoP\001Z)cerence/cloudservices/api/services/asr/v1'
  _globals['_FORMATWORD']._serialized_start=227
  _globals['_FORMATWORD']._serialized_end=425
# @@protoc_insertion_point(module_scope)
