# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/services/asr/v1/spoken_form.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/services/asr/v1/spoken_form.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;cerence/cloudservices/api/services/asr/v1/spoken_form.proto\x12)cerence.cloudservices.api.services.asr.v1\x1a\x1fgoogle/api/field_behavior.proto\"*\n\x0eWordSpokenForm\x12\x18\n\ntranscript\x18\x01 \x01(\tB\x04\xe2\x41\x01\x02\x42m\n-com.cerence.cloudservices.api.services.asr.v1B\x0fSpokenFormProtoP\x01Z)cerence/cloudservices/api/services/asr/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.asr.v1.spoken_form_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.cerence.cloudservices.api.services.asr.v1B\017SpokenFormProtoP\001Z)cerence/cloudservices/api/services/asr/v1'
  _globals['_WORDSPOKENFORM'].fields_by_name['transcript']._loaded_options = None
  _globals['_WORDSPOKENFORM'].fields_by_name['transcript']._serialized_options = b'\342A\001\002'
  _globals['_WORDSPOKENFORM']._serialized_start=139
  _globals['_WORDSPOKENFORM']._serialized_end=181
# @@protoc_insertion_point(module_scope)
