# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/communication/v1/communication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/communication/v1/communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPcerence/cloudservices/domain/common/content/communication/v1/communication.proto\x12<cerence.cloudservices.domain.common.content.communication.v1\"\x84\x01\n\x14\x43ommunicationContent\x12l\n\x07\x63ontact\x18\x01 \x01(\x0b\x32[.cerence.cloudservices.domain.common.content.communication.v1.CommunicationContactGrounding\"\x82\x01\n\x1d\x43ommunicationContactGrounding\x12\x61\n\tgrounding\x18\x01 \x03(\x0b\x32N.cerence.cloudservices.domain.common.content.communication.v1.ContactGrounding\"S\n\x10\x43ontactGrounding\x12\x12\n\nconcept_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63oncept_version\x18\x02 \x01(\x05\x12\x12\n\ncontact_id\x18\x03 \x03(\tB\x9d\x01\n@com.cerence.cloudservices.domain.common.content.communication.v1B\x19\x43ommunicationContentProtoP\x01Z<cerence/cloudservices/domain/common/content/communication/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.communication.v1.communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n@com.cerence.cloudservices.domain.common.content.communication.v1B\031CommunicationContentProtoP\001Z<cerence/cloudservices/domain/common/content/communication/v1'
  _globals['_COMMUNICATIONCONTENT']._serialized_start=147
  _globals['_COMMUNICATIONCONTENT']._serialized_end=279
  _globals['_COMMUNICATIONCONTACTGROUNDING']._serialized_start=282
  _globals['_COMMUNICATIONCONTACTGROUNDING']._serialized_end=412
  _globals['_CONTACTGROUNDING']._serialized_start=414
  _globals['_CONTACTGROUNDING']._serialized_end=497
# @@protoc_insertion_point(module_scope)
