# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cerence.cloudservices.api.services.data_exchange.v1 import data_exchange_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_data__exchange_dot_v1_dot_data__exchange__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cerence/cloudservices/api/services/data_exchange/v1/data_exchange_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataExchangeServiceStub(object):
    """Service that implements the Cerence API for Data Exchange requests
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DataExchange = channel.unary_stream(
                '/cerence.cloudservices.api.services.data_exchange.v1.DataExchangeService/DataExchange',
                request_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_data__exchange_dot_v1_dot_data__exchange__pb2.DataExchangeRequest.SerializeToString,
                response_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_data__exchange_dot_v1_dot_data__exchange__pb2.DataExchangeResponse.FromString,
                _registered_method=True)


class DataExchangeServiceServicer(object):
    """Service that implements the Cerence API for Data Exchange requests
    """

    def DataExchange(self, request, context):
        """Performs a Data Exchange request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DataExchange': grpc.unary_stream_rpc_method_handler(
                    servicer.DataExchange,
                    request_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_data__exchange_dot_v1_dot_data__exchange__pb2.DataExchangeRequest.FromString,
                    response_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_data__exchange_dot_v1_dot_data__exchange__pb2.DataExchangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cerence.cloudservices.api.services.data_exchange.v1.DataExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cerence.cloudservices.api.services.data_exchange.v1.DataExchangeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataExchangeService(object):
    """Service that implements the Cerence API for Data Exchange requests
    """

    @staticmethod
    def DataExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cerence.cloudservices.api.services.data_exchange.v1.DataExchangeService/DataExchange',
            cerence_dot_cloudservices_dot_api_dot_services_dot_data__exchange_dot_v1_dot_data__exchange__pb2.DataExchangeRequest.SerializeToString,
            cerence_dot_cloudservices_dot_api_dot_services_dot_data__exchange_dot_v1_dot_data__exchange__pb2.DataExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
