# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/weather/v1/daily_forecast.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.weather.v1 import common_detail_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_weather_dot_v1_dot_common__detail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKcerence/cloudservices/domain/common/content/weather/v1/daily_forecast.proto\x12\x36\x63\x65rence.cloudservices.domain.common.content.weather.v1\x1aJcerence/cloudservices/domain/common/content/weather/v1/common_detail.proto\"\xd6\x04\n\rDailyForecast\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x61y_of_week\x18\x02 \x01(\t\x12\x0f\n\x07sunrise\x18\x03 \x01(\t\x12\x0e\n\x06sunset\x18\x04 \x01(\t\x12]\n\x0btemperature\x18\x05 \x01(\x0b\x32H.cerence.cloudservices.domain.common.content.weather.v1.MeasurementRange\x12\\\n\nfeels_like\x18\x06 \x01(\x0b\x32H.cerence.cloudservices.domain.common.content.weather.v1.MeasurementRange\x12\x46\n\x02uv\x18\x07 \x01(\x0b\x32:.cerence.cloudservices.domain.common.content.weather.v1.UV\x12M\n\x03\x64\x61y\x18\x08 \x01(\x0b\x32@.cerence.cloudservices.domain.common.content.weather.v1.DayNight\x12O\n\x05night\x18\t \x01(\x0b\x32@.cerence.cloudservices.domain.common.content.weather.v1.DayNight\x12\\\n\rprecipitation\x18\n \x01(\x0b\x32\x45.cerence.cloudservices.domain.common.content.weather.v1.PrecipitationB\x8a\x01\n:com.cerence.cloudservices.domain.common.content.weather.v1B\x12\x44\x61ilyForecastProtoP\x01Z6cerence/cloudservices/domain/common/content/weather/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.weather.v1.daily_forecast_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n:com.cerence.cloudservices.domain.common.content.weather.v1B\022DailyForecastProtoP\001Z6cerence/cloudservices/domain/common/content/weather/v1'
  _DAILYFORECAST._serialized_start=212
  _DAILYFORECAST._serialized_end=810
# @@protoc_insertion_point(module_scope)
