# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/weather/v1/ski_conditions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.common.v1 import common_detail_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_common_dot_v1_dot_common__detail__pb2
from cerence.cloudservices.domain.common.content.common.v1 import content_status_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_common_dot_v1_dot_content__status__pb2
from cerence.cloudservices.domain.common.content.weather.v1 import ski_area_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_weather_dot_v1_dot_ski__area__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKcerence/cloudservices/domain/common/content/weather/v1/ski_conditions.proto\x12\x36\x63\x65rence.cloudservices.domain.common.content.weather.v1\x1aIcerence/cloudservices/domain/common/content/common/v1/common_detail.proto\x1aJcerence/cloudservices/domain/common/content/common/v1/content_status.proto\x1a\x45\x63\x65rence/cloudservices/domain/common/content/weather/v1/ski_area.proto\"\xa4\x02\n\rSkiConditions\x12R\n\tski_areas\x18\x01 \x03(\x0b\x32?.cerence.cloudservices.domain.common.content.weather.v1.SkiArea\x12X\n\x0c\x61ttributions\x18\x02 \x03(\x0b\x32\x42.cerence.cloudservices.domain.common.content.common.v1.Attribution\x12\x65\n\x13\x63ontent_status_info\x18\x03 \x01(\x0b\x32H.cerence.cloudservices.domain.common.content.common.v1.ContentStatusInfoB\x8a\x01\n:com.cerence.cloudservices.domain.common.content.weather.v1B\x12SkiConditionsProtoP\x01Z6cerence/cloudservices/domain/common/content/weather/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.weather.v1.ski_conditions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n:com.cerence.cloudservices.domain.common.content.weather.v1B\022SkiConditionsProtoP\001Z6cerence/cloudservices/domain/common/content/weather/v1'
  _SKICONDITIONS._serialized_start=358
  _SKICONDITIONS._serialized_end=650
# @@protoc_insertion_point(module_scope)
