# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/weather/v1/weather_summary.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.common.v1 import common_detail_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_common_dot_v1_dot_common__detail__pb2
from cerence.cloudservices.domain.common.content.common.v1 import content_status_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_common_dot_v1_dot_content__status__pb2
from cerence.cloudservices.domain.common.content.weather.v1 import current_conditions_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_weather_dot_v1_dot_current__conditions__pb2
from cerence.cloudservices.domain.common.content.weather.v1 import daily_forecast_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_weather_dot_v1_dot_daily__forecast__pb2
from cerence.cloudservices.domain.common.content.weather.v1 import hourly_forecast_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_weather_dot_v1_dot_hourly__forecast__pb2
from cerence.cloudservices.domain.common.content.weather.v1 import weather_focus_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_weather_dot_v1_dot_weather__focus__pb2
from cerence.cloudservices.domain.common.content.weather.v1 import weather_location_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_weather_dot_v1_dot_weather__location__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLcerence/cloudservices/domain/common/content/weather/v1/weather_summary.proto\x12\x36\x63\x65rence.cloudservices.domain.common.content.weather.v1\x1aIcerence/cloudservices/domain/common/content/common/v1/common_detail.proto\x1aJcerence/cloudservices/domain/common/content/common/v1/content_status.proto\x1aOcerence/cloudservices/domain/common/content/weather/v1/current_conditions.proto\x1aKcerence/cloudservices/domain/common/content/weather/v1/daily_forecast.proto\x1aLcerence/cloudservices/domain/common/content/weather/v1/hourly_forecast.proto\x1aJcerence/cloudservices/domain/common/content/weather/v1/weather_focus.proto\x1aMcerence/cloudservices/domain/common/content/weather/v1/weather_location.proto\"\xb2\x05\n\x0eWeatherSummary\x12[\n\rweather_focus\x18\x01 \x01(\x0b\x32\x44.cerence.cloudservices.domain.common.content.weather.v1.WeatherFocus\x12Y\n\x08location\x18\x02 \x01(\x0b\x32G.cerence.cloudservices.domain.common.content.weather.v1.WeatherLocation\x12\x65\n\x12\x63urrent_conditions\x18\x03 \x01(\x0b\x32I.cerence.cloudservices.domain.common.content.weather.v1.CurrentConditions\x12^\n\x0f\x64\x61ily_forecasts\x18\x04 \x03(\x0b\x32\x45.cerence.cloudservices.domain.common.content.weather.v1.DailyForecast\x12`\n\x10hourly_forecasts\x18\x05 \x03(\x0b\x32\x46.cerence.cloudservices.domain.common.content.weather.v1.HourlyForecast\x12X\n\x0c\x61ttributions\x18\x06 \x03(\x0b\x32\x42.cerence.cloudservices.domain.common.content.common.v1.Attribution\x12\x65\n\x13\x63ontent_status_info\x18\x07 \x01(\x0b\x32H.cerence.cloudservices.domain.common.content.common.v1.ContentStatusInfoB\x8b\x01\n:com.cerence.cloudservices.domain.common.content.weather.v1B\x13WeatherSummaryProtoP\x01Z6cerence/cloudservices/domain/common/content/weather/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.weather.v1.weather_summary_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n:com.cerence.cloudservices.domain.common.content.weather.v1B\023WeatherSummaryProtoP\001Z6cerence/cloudservices/domain/common/content/weather/v1'
  _WEATHERSUMMARY._serialized_start=679
  _WEATHERSUMMARY._serialized_end=1369
# @@protoc_insertion_point(module_scope)
