# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/domain/common/content/weather/v1/weather_location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import latlng_pb2 as google_dot_type_dot_latlng__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMcerence/cloudservices/domain/common/content/weather/v1/weather_location.proto\x12\x36\x63\x65rence.cloudservices.domain.common.content.weather.v1\x1a\x18google/type/latlng.proto\"\x80\x01\n\x0fWeatherLocation\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x14\n\x0cneighborhood\x18\x04 \x01(\t\x12)\n\x0cgeo_position\x18\x05 \x01(\x0b\x32\x13.google.type.LatLngB\x8c\x01\n:com.cerence.cloudservices.domain.common.content.weather.v1B\x14WeatherLocationProtoP\x01Z6cerence/cloudservices/domain/common/content/weather/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.weather.v1.weather_location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n:com.cerence.cloudservices.domain.common.content.weather.v1B\024WeatherLocationProtoP\001Z6cerence/cloudservices/domain/common/content/weather/v1'
  _WEATHERLOCATION._serialized_start=164
  _WEATHERLOCATION._serialized_end=292
# @@protoc_insertion_point(module_scope)
