# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/ude/v1/multimodal_detail.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/ude/v1/multimodal_detail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJcerence/cloudservices/domain/common/content/ude/v1/multimodal_detail.proto\x12\x32\x63\x65rence.cloudservices.domain.common.content.ude.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\xe2\x01\n\x10MultimodalDetail\x12\x36\n\x10visibility_score\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x35\n\x0finclusion_score\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x31\n\x0b\x62uilding_id\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06poi_id\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\x85\x01\n6com.cerence.cloudservices.domain.common.content.ude.v1B\x15MultimodalDetailProtoP\x01Z2cerence/cloudservices/domain/common/content/ude/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.ude.v1.multimodal_detail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n6com.cerence.cloudservices.domain.common.content.ude.v1B\025MultimodalDetailProtoP\001Z2cerence/cloudservices/domain/common/content/ude/v1'
  _globals['_MULTIMODALDETAIL']._serialized_start=163
  _globals['_MULTIMODALDETAIL']._serialized_end=389
# @@protoc_insertion_point(module_scope)
