# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/ude/v1/traffic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/ude/v1/traffic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.ude.v1 import place_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_ude_dot_v1_dot_place__pb2
from cerence.cloudservices.domain.common.content.common.v1 import content_status_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_common_dot_v1_dot_content__status__pb2
from cerence.cloudservices.domain.common.content.ude.v1 import meta_info_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_ude_dot_v1_dot_meta__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@cerence/cloudservices/domain/common/content/ude/v1/traffic.proto\x12\x32\x63\x65rence.cloudservices.domain.common.content.ude.v1\x1a>cerence/cloudservices/domain/common/content/ude/v1/place.proto\x1aJcerence/cloudservices/domain/common/content/common/v1/content_status.proto\x1a\x42\x63\x65rence/cloudservices/domain/common/content/ude/v1/meta_info.proto\"\xe4\x02\n\x07Traffic\x12\x65\n\x13\x63ontent_status_info\x18\x01 \x01(\x0b\x32H.cerence.cloudservices.domain.common.content.common.v1.ContentStatusInfo\x12J\n\x07origins\x18\x02 \x03(\x0b\x32\x39.cerence.cloudservices.domain.common.content.ude.v1.Place\x12O\n\x0c\x64\x65stinations\x18\x03 \x03(\x0b\x32\x39.cerence.cloudservices.domain.common.content.ude.v1.Place\x12U\n\tmeta_info\x18\x04 \x01(\x0b\x32\x42.cerence.cloudservices.domain.common.content.ude.v1.GlobalMetaInfoB|\n6com.cerence.cloudservices.domain.common.content.ude.v1B\x0cTrafficProtoP\x01Z2cerence/cloudservices/domain/common/content/ude/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.ude.v1.traffic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n6com.cerence.cloudservices.domain.common.content.ude.v1B\014TrafficProtoP\001Z2cerence/cloudservices/domain/common/content/ude/v1'
  _globals['_TRAFFIC']._serialized_start=329
  _globals['_TRAFFIC']._serialized_end=685
# @@protoc_insertion_point(module_scope)
