# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/api/services/tts/v1/tts_input_type.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/api/services/tts/v1/tts_input_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>cerence/cloudservices/api/services/tts/v1/tts_input_type.proto\x12)cerence.cloudservices.api.services.tts.v1*`\n\x0cTtsInputType\x12\x1e\n\x1aTTS_INPUT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13TTS_INPUT_TYPE_TEXT\x10\x01\x12\x17\n\x13TTS_INPUT_TYPE_SSML\x10\x02\x42o\n-com.cerence.cloudservices.api.services.tts.v1B\x11TtsInputTypeProtoP\x01Z)cerence/cloudservices/api/services/tts/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.tts.v1.tts_input_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.cerence.cloudservices.api.services.tts.v1B\021TtsInputTypeProtoP\001Z)cerence/cloudservices/api/services/tts/v1'
  _globals['_TTSINPUTTYPE']._serialized_start=109
  _globals['_TTSINPUTTYPE']._serialized_end=205
# @@protoc_insertion_point(module_scope)
