# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerence/cloudservices/api/services/tps_minimono/v1/tps_spoken_form.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHcerence/cloudservices/api/services/tps_minimono/v1/tps_spoken_form.proto\x12\x32\x63\x65rence.cloudservices.api.services.tps_minimono.v1\"%\n\x0eWordSpokenForm\x12\x13\n\x0btranscripts\x18\x03 \x03(\tB\x85\x01\n6com.cerence.cloudservices.api.services.tps_minimono.v1B\x12TpsSpokenFormProtoP\x01Z2cerence/cloudservices/api/services/tps_minimono/v1\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.api.services.tps_minimono.v1.tps_spoken_form_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n6com.cerence.cloudservices.api.services.tps_minimono.v1B\022TpsSpokenFormProtoP\001Z2cerence/cloudservices/api/services/tps_minimono/v1\370\001\001'
  _WORDSPOKENFORM._serialized_start=128
  _WORDSPOKENFORM._serialized_end=165
# @@protoc_insertion_point(module_scope)
