# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/media/v1/amazon_music.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/media/v1/amazon_music.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGcerence/cloudservices/domain/common/content/media/v1/amazon_music.proto\x12\x34\x63\x65rence.cloudservices.domain.common.content.media.v1\"\"\n\x13\x41mazonMusicMetadata\x12\x0b\n\x03url\x18\x01 \x01(\tB\x84\x01\n8com.cerence.cloudservices.domain.common.content.media.v1B\x10\x41mazonMusicProtoP\x01Z4cerence/cloudservices/domain/common/content/media/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.media.v1.amazon_music_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8com.cerence.cloudservices.domain.common.content.media.v1B\020AmazonMusicProtoP\001Z4cerence/cloudservices/domain/common/content/media/v1'
  _globals['_AMAZONMUSICMETADATA']._serialized_start=129
  _globals['_AMAZONMUSICMETADATA']._serialized_end=163
# @@protoc_insertion_point(module_scope)
