# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/media/v1/episode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/media/v1/episode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.media.v1 import visual_content_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_visual__content__pb2
from cerence.cloudservices.domain.common.content.media.v1 import sirius_xm_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_sirius__xm__pb2
from cerence.cloudservices.domain.common.content.media.v1 import languages_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_languages__pb2
from cerence.cloudservices.domain.common.content.media.v1 import show_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_show__pb2
from cerence.cloudservices.domain.common.content.media.v1 import spotify_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_spotify__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBcerence/cloudservices/domain/common/content/media/v1/episode.proto\x12\x34\x63\x65rence.cloudservices.domain.common.content.media.v1\x1aIcerence/cloudservices/domain/common/content/media/v1/visual_content.proto\x1a\x44\x63\x65rence/cloudservices/domain/common/content/media/v1/sirius_xm.proto\x1a\x44\x63\x65rence/cloudservices/domain/common/content/media/v1/languages.proto\x1a?cerence/cloudservices/domain/common/content/media/v1/show.proto\x1a\x42\x63\x65rence/cloudservices/domain/common/content/media/v1/spotify.proto\"\xf1\x04\n\x07\x45pisode\x12X\n\tbase_info\x18\x01 \x01(\x0b\x32\x45.cerence.cloudservices.domain.common.content.media.v1.EpisodeBaseInfo\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\x12\r\n\x05guest\x18\x05 \x03(\t\x12R\n\x05media\x18\x06 \x03(\x0b\x32\x43.cerence.cloudservices.domain.common.content.media.v1.VisualContent\x12Q\n\tlanguages\x18\x07 \x03(\x0b\x32>.cerence.cloudservices.domain.common.content.media.v1.Language\x12h\n\x12sirius_xm_metadata\x18\x08 \x01(\x0b\x32J.cerence.cloudservices.domain.common.content.media.v1.SiriusXMShowMetadataH\x00\x12\x61\n\x10spotify_metadata\x18\t \x01(\x0b\x32\x45.cerence.cloudservices.domain.common.content.media.v1.SpotifyMetadataH\x00\x12Z\n\x0eshow_base_info\x18\n \x01(\x0b\x32\x42.cerence.cloudservices.domain.common.content.media.v1.ShowBaseInfoB\n\n\x08metadata\"+\n\x0f\x45pisodeBaseInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tB\x80\x01\n8com.cerence.cloudservices.domain.common.content.media.v1B\x0c\x45pisodeProtoP\x01Z4cerence/cloudservices/domain/common/content/media/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.media.v1.episode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8com.cerence.cloudservices.domain.common.content.media.v1B\014EpisodeProtoP\001Z4cerence/cloudservices/domain/common/content/media/v1'
  _globals['_EPISODE']._serialized_start=473
  _globals['_EPISODE']._serialized_end=1098
  _globals['_EPISODEBASEINFO']._serialized_start=1100
  _globals['_EPISODEBASEINFO']._serialized_end=1143
# @@protoc_insertion_point(module_scope)
