# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerence/cloudservices/domain/common/content/media/v1/radio_station.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cerence/cloudservices/domain/common/content/media/v1/radio_station.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerence.cloudservices.domain.common.content.media.v1 import visual_content_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_visual__content__pb2
from cerence.cloudservices.domain.common.content.media.v1 import amazon_music_pb2 as cerence_dot_cloudservices_dot_domain_dot_common_dot_content_dot_media_dot_v1_dot_amazon__music__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHcerence/cloudservices/domain/common/content/media/v1/radio_station.proto\x12\x34\x63\x65rence.cloudservices.domain.common.content.media.v1\x1aIcerence/cloudservices/domain/common/content/media/v1/visual_content.proto\x1aGcerence/cloudservices/domain/common/content/media/v1/amazon_music.proto\"\xb9\x02\n\x0cRadioStation\x12]\n\tbase_info\x18\x01 \x01(\x0b\x32J.cerence.cloudservices.domain.common.content.media.v1.RadioStationBaseInfo\x12R\n\x05media\x18\x02 \x03(\x0b\x32\x43.cerence.cloudservices.domain.common.content.media.v1.VisualContent\x12j\n\x15\x61mazon_music_metadata\x18\x03 \x01(\x0b\x32I.cerence.cloudservices.domain.common.content.media.v1.AmazonMusicMetadataH\x00\x42\n\n\x08metadata\"0\n\x14RadioStationBaseInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tB\x85\x01\n8com.cerence.cloudservices.domain.common.content.media.v1B\x11RadioStationProtoP\x01Z4cerence/cloudservices/domain/common/content/media/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerence.cloudservices.domain.common.content.media.v1.radio_station_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8com.cerence.cloudservices.domain.common.content.media.v1B\021RadioStationProtoP\001Z4cerence/cloudservices/domain/common/content/media/v1'
  _globals['_RADIOSTATION']._serialized_start=279
  _globals['_RADIOSTATION']._serialized_end=592
  _globals['_RADIOSTATIONBASEINFO']._serialized_start=594
  _globals['_RADIOSTATIONBASEINFO']._serialized_end=642
# @@protoc_insertion_point(module_scope)
