# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cerence.cloudservices.api.services.user_data.v1 import user_data_api_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_user__data_dot_v1_dot_user__data__api__pb2
from cerence.cloudservices.api.services.user_data_minimono.v1 import user_data_upload_api_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cerence/cloudservices/api/services/user_data_minimono/v1/user_data_upload_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class UserDataUploadMiniMonoServiceStub(object):
    """Service that implements the Cerence API for NCS User Data requests
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamingFullUpload = channel.stream_stream(
                '/cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService/StreamingFullUpload',
                request_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.StreamingFullUploadRequest.SerializeToString,
                response_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data_dot_v1_dot_user__data__api__pb2.StreamingFullUploadResponse.FromString,
                _registered_method=True)
        self.IncrementalUpload = channel.stream_stream(
                '/cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService/IncrementalUpload',
                request_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.IncrementalUploadRequest.SerializeToString,
                response_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.IncrementalUploadResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_stream(
                '/cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService/Delete',
                request_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.DeleteRequest.SerializeToString,
                response_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data_dot_v1_dot_user__data__api__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_stream(
                '/cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService/GetVersion',
                request_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.GetVersionResponse.FromString,
                _registered_method=True)


class UserDataUploadMiniMonoServiceServicer(object):
    """Service that implements the Cerence API for NCS User Data requests
    """

    def StreamingFullUpload(self, request_iterator, context):
        """Performs streaming upload user raw data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementalUpload(self, request_iterator, context):
        """performs synchronous incremental upload user raw data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete user data including raw data and vary&inflect data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Get data version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserDataUploadMiniMonoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamingFullUpload': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingFullUpload,
                    request_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.StreamingFullUploadRequest.FromString,
                    response_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data_dot_v1_dot_user__data__api__pb2.StreamingFullUploadResponse.SerializeToString,
            ),
            'IncrementalUpload': grpc.stream_stream_rpc_method_handler(
                    servicer.IncrementalUpload,
                    request_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.IncrementalUploadRequest.FromString,
                    response_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.IncrementalUploadResponse.SerializeToString,
            ),
            'Delete': grpc.unary_stream_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.DeleteRequest.FromString,
                    response_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data_dot_v1_dot_user__data__api__pb2.DeleteResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.GetVersionRequest.FromString,
                    response_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserDataUploadMiniMonoService(object):
    """Service that implements the Cerence API for NCS User Data requests
    """

    @staticmethod
    def StreamingFullUpload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService/StreamingFullUpload',
            cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.StreamingFullUploadRequest.SerializeToString,
            cerence_dot_cloudservices_dot_api_dot_services_dot_user__data_dot_v1_dot_user__data__api__pb2.StreamingFullUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementalUpload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService/IncrementalUpload',
            cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.IncrementalUploadRequest.SerializeToString,
            cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.IncrementalUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService/Delete',
            cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.DeleteRequest.SerializeToString,
            cerence_dot_cloudservices_dot_api_dot_services_dot_user__data_dot_v1_dot_user__data__api__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cerence.cloudservices.api.services.user_data_minimono.v1.UserDataUploadMiniMonoService/GetVersion',
            cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.GetVersionRequest.SerializeToString,
            cerence_dot_cloudservices_dot_api_dot_services_dot_user__data__minimono_dot_v1_dot_user__data__upload__api__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
