# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cerence.cloudservices.api.services.tts_minimono.v1 import tts_api_pb2 as cerence_dot_cloudservices_dot_api_dot_services_dot_tts__minimono_dot_v1_dot_tts__api__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cerence/cloudservices/api/services/tts_minimono/v1/tts_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TtsMiniMonoServiceStub(object):
    """Service that implements the Cerence API for NCS TTS requests
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TtsQuery = channel.unary_stream(
                '/cerence.cloudservices.api.services.tts_minimono.v1.TtsMiniMonoService/TtsQuery',
                request_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_tts__minimono_dot_v1_dot_tts__api__pb2.TtsQueryRequest.SerializeToString,
                response_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_tts__minimono_dot_v1_dot_tts__api__pb2.StreamingTtsQueryResponse.FromString,
                _registered_method=True)


class TtsMiniMonoServiceServicer(object):
    """Service that implements the Cerence API for NCS TTS requests
    """

    def TtsQuery(self, request, context):
        """Performs an TTS query request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TtsMiniMonoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TtsQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.TtsQuery,
                    request_deserializer=cerence_dot_cloudservices_dot_api_dot_services_dot_tts__minimono_dot_v1_dot_tts__api__pb2.TtsQueryRequest.FromString,
                    response_serializer=cerence_dot_cloudservices_dot_api_dot_services_dot_tts__minimono_dot_v1_dot_tts__api__pb2.StreamingTtsQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cerence.cloudservices.api.services.tts_minimono.v1.TtsMiniMonoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cerence.cloudservices.api.services.tts_minimono.v1.TtsMiniMonoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TtsMiniMonoService(object):
    """Service that implements the Cerence API for NCS TTS requests
    """

    @staticmethod
    def TtsQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cerence.cloudservices.api.services.tts_minimono.v1.TtsMiniMonoService/TtsQuery',
            cerence_dot_cloudservices_dot_api_dot_services_dot_tts__minimono_dot_v1_dot_tts__api__pb2.TtsQueryRequest.SerializeToString,
            cerence_dot_cloudservices_dot_api_dot_services_dot_tts__minimono_dot_v1_dot_tts__api__pb2.StreamingTtsQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
